// Auto-generated by jiatingbao_slicer.py — 家庭包访谈原声切片映射
import type { EvidenceClip } from './evidenceClipLookup';

export const JIATINGBAO_CLIP_MAP: Record<string, EvidenceClip> =
{
  "姐姐上高中没精力管他了，会把更多精力放在小的身上。": {
    "clipUrl": "/clips/jiatingbao/user3/0001.mp3",
    "startTime": 2722.8,
    "duration": 11.8
  },
  "不需要接送，孩子也不用赶路，时间成本也没有，还比私教班便宜，私教班一门就一万多。": {
    "clipUrl": "/clips/jiatingbao/user3/0002.mp3",
    "startTime": 4117.2,
    "duration": 5.1
  },
  "小升初的时候没有给报，现在想起来有点后悔。": {
    "clipUrl": "/clips/jiatingbao/user3/0003.mp3",
    "startTime": 1494.3,
    "duration": 11.9
  },
  "阿刘教育规划训练营……只是单纯说这个好、提供链接，从客观公正的角度说，比起销售更相信他。": {
    "clipUrl": "/clips/jiatingbao/user4/0001.mp3",
    "startTime": 2802.1,
    "duration": 7.3
  },
  "希望 2 个孩子一起用，账号不会相互冲突，希望能发挥到最大的功效。": {
    "clipUrl": "/clips/jiatingbao/user4/0002.mp3",
    "startTime": 2227.9,
    "duration": 8.2
  },
  "如果 2 个不能同时用，就不考虑了。": {
    "clipUrl": "/clips/jiatingbao/user4/0003.mp3",
    "startTime": 2607.9,
    "duration": 5.8
  },
  "现在先学 5 年级内容复习，寒暑假预习 6 年级内容。": {
    "clipUrl": "/clips/jiatingbao/user5/0001.mp3",
    "startTime": 1897.8,
    "duration": 4.1
  },
  "买小学+初中的会有浪费，反而还有 1 年不够用。": {
    "clipUrl": "/clips/jiatingbao/user5/0002.mp3",
    "startTime": 1230.9,
    "duration": 3.4
  },
  "以后会价格更贵，因为套餐分开买更贵。": {
    "clipUrl": "/clips/jiatingbao/user5/0003.mp3",
    "startTime": 2111.3,
    "duration": 9.3
  },
  "花这么多钱不一定能见到提分效果。": {
    "clipUrl": "/clips/jiatingbao/user6/0001.mp3",
    "startTime": 785.5,
    "duration": 3.5
  },
  "想等有效果才买（高中的），数学要至少到 90 分以上。": {
    "clipUrl": "/clips/jiatingbao/user6/0002.mp3",
    "startTime": 1707.1,
    "duration": 12.6
  },
  "风格好，不粗糙，孩子感兴趣，抽象的知识点能讲解出来。": {
    "clipUrl": "/clips/jiatingbao/user7/0001.mp3",
    "startTime": 1118.2,
    "duration": 13.4
  },
  "将一个抽象的东西具体化，对孩子理解好。": {
    "clipUrl": "/clips/jiatingbao/user7/0002.mp3",
    "startTime": 758.6,
    "duration": 6.8
  },
  "看着看着没兴趣——这个更重要，买了不看再好也没用。": {
    "clipUrl": "/clips/jiatingbao/user7/0003.mp3",
    "startTime": 1887.7,
    "duration": 5.4
  },
  "他丢个文件夹给你点开看，跟报了课看的感觉不一样……没有输出就是盲目接收。": {
    "clipUrl": "/clips/jiatingbao/user8/0001.mp3",
    "startTime": 1738.9,
    "duration": 7.7
  },
  "几个孩子同时在房间学完，就能一起出发……我孩子多就会想到这些。": {
    "clipUrl": "/clips/jiatingbao/user8/0002.mp3",
    "startTime": 3497.4,
    "duration": 4.4
  },
  "如果有效果，我会排除万难让他们学下去。": {
    "clipUrl": "/clips/jiatingbao/user8/0003.mp3",
    "startTime": 2772.2,
    "duration": 5.1
  }
}
;
