// Auto-generated by jiatingbao_slicer.py — 家庭包原声->切片（caption 为 key）
import type { EvidenceClip } from './evidenceClipLookup';

export const JIATINGBAO_CLIP_MAP: Record<string, EvidenceClip> =
{
  "怕数学基础没打好，五六年级会更难搞。": {
    "clipUrl": "/clips/jiatingbao/user1/0001.mp3",
    "startTime": 988.9,
    "duration": 5.3
  },
  "担忧买了浪费、孩子不能坚持；最终打消是因为哥哥自己说喜欢学。": {
    "clipUrl": "/clips/jiatingbao/user1/0002.mp3",
    "startTime": 2031.0,
    "duration": 12.4
  },
  "小学语文拔尖，初中优势没发挥出来；生物地理较好，喜欢课外知识。": {
    "clipUrl": "/clips/jiatingbao/user2/0001.mp3",
    "startTime": 631.3,
    "duration": 8.5
  },
  "爸爸看了几天、在洋葱里比较是否适合；认为洋葱最强是数学（前身洋葱数学）。": {
    "clipUrl": "/clips/jiatingbao/user2/0002.mp3",
    "startTime": 801.9,
    "duration": 13.7
  },
  "诉求：要超前学一些拔高、难一点的内容，不能只和学校同步。": {
    "clipUrl": "/clips/jiatingbao/user2/0003.mp3",
    "startTime": 923.8,
    "duration": 9.5
  },
  "超前学能消化吸收，培养的知识能成体系（自己总结主线、串联知识）。": {
    "clipUrl": "/clips/jiatingbao/user2/0004.mp3",
    "startTime": 1620.2,
    "duration": 12.7
  },
  "不只是教孩子套什么公式、教你怎么解题，而是要提高孩子的思维分析能力。": {
    "clipUrl": "/clips/jiatingbao/user2/0005.mp3",
    "startTime": 1756.4,
    "duration": 10.5
  },
  "不只是套公式，而是提高思维分析能力、培养自主思考与举一反三的能力。": {
    "clipUrl": "/clips/jiatingbao/user2/0006.mp3",
    "startTime": 1780.5,
    "duration": 14.0
  },
  "既然要提前学就一起买，初中的时候就要往高中的时候学，不能等到了高中再学。": {
    "clipUrl": "/clips/jiatingbao/user2/0007.mp3",
    "startTime": 2848.6,
    "duration": 6.3
  },
  "小升初的时候没有给报，现在想起来有点后悔。": {
    "clipUrl": "/clips/jiatingbao/user3/0001.mp3",
    "startTime": 1494.5,
    "duration": 11.5
  },
  "价格焦虑：去年价格低没买，后来涨价很多，吃过一次亏，这次先买。": {
    "clipUrl": "/clips/jiatingbao/user3/0002.mp3",
    "startTime": 2127.4,
    "duration": 11.9
  },
  "姐姐上高中没精力管他了，会把更多精力放在小的身上。": {
    "clipUrl": "/clips/jiatingbao/user3/0003.mp3",
    "startTime": 2725.5,
    "duration": 8.9
  },
  "不需要接送，孩子也不用赶路，时间成本也没有，还比私教班便宜，私教班一门就一万多。": {
    "clipUrl": "/clips/jiatingbao/user3/0004.mp3",
    "startTime": 4115.2,
    "duration": 6.9
  },
  "希望 2 个孩子一起用，账号不会相互冲突，希望能发挥到最大的功效。": {
    "clipUrl": "/clips/jiatingbao/user4/0001.mp3",
    "startTime": 2228.1,
    "duration": 7.8
  },
  "如果 2 个不能同时用，就不考虑了。": {
    "clipUrl": "/clips/jiatingbao/user4/0002.mp3",
    "startTime": 2608.1,
    "duration": 5.4
  },
  "买小学+初中的会有浪费，反而还有 1 年不够用。": {
    "clipUrl": "/clips/jiatingbao/user5/0001.mp3",
    "startTime": 1225.7,
    "duration": 5.1
  },
  "让孩子体验过、孩子喜欢才买；销售说什么课都有、时间长。": {
    "clipUrl": "/clips/jiatingbao/user5/0002.mp3",
    "startTime": 1382.4,
    "duration": 7.5
  },
  "现在先学 5 年级内容复习，寒暑假预习 6 年级内容。": {
    "clipUrl": "/clips/jiatingbao/user5/0003.mp3",
    "startTime": 1882.2,
    "duration": 6.0
  },
  "以后会价格更贵，因为套餐分开买更贵。": {
    "clipUrl": "/clips/jiatingbao/user5/0004.mp3",
    "startTime": 2117.9,
    "duration": 2.6
  },
  "将一个抽象的东西具体化，对孩子理解好。": {
    "clipUrl": "/clips/jiatingbao/user7/0001.mp3",
    "startTime": 758.8,
    "duration": 6.4
  },
  "课程可学 6 年（本来高中只能学两年）。": {
    "clipUrl": "/clips/jiatingbao/user7/0002.mp3",
    "startTime": 1756.1,
    "duration": 6.4
  },
  "看着看着没兴趣——这个更重要，买了不看再好也没用。": {
    "clipUrl": "/clips/jiatingbao/user7/0003.mp3",
    "startTime": 1884.4,
    "duration": 8.4
  },
  "他丢个文件夹给你点开看，跟报了课看的感觉不一样……没有输出就是盲目接收。": {
    "clipUrl": "/clips/jiatingbao/user8/0001.mp3",
    "startTime": 1736.1,
    "duration": 10.3
  },
  "暂以期末考试结果作为短期验证。": {
    "clipUrl": "/clips/jiatingbao/user8/0002.mp3",
    "startTime": 2737.6,
    "duration": 7.1
  },
  "如果有效果，我会排除万难让他们学下去。": {
    "clipUrl": "/clips/jiatingbao/user8/0003.mp3",
    "startTime": 2772.4,
    "duration": 4.7
  },
  "几个孩子同时在房间学完，就能一起出发……我孩子多就会想到这些。": {
    "clipUrl": "/clips/jiatingbao/user8/0004.mp3",
    "startTime": 3497.6,
    "duration": 5.3
  },
  "大宝主要用 + 小宝顺带用。": {
    "clipUrl": "/clips/jiatingbao/user6/0001.mp3",
    "startTime": 414.2,
    "duration": 1.4
  },
  "花这么多钱不一定能见到提分效果。": {
    "clipUrl": "/clips/jiatingbao/user6/0002.mp3",
    "startTime": 785.7,
    "duration": 2.1
  }
}
;
