// Auto-generated by jiatingbao_reslice.py — 家庭包逐字原声切片（按维度）
export interface JtbVoiceClip {
  seq: number;
  dimension: string;
  caption: string;
  text: string;
  clipUrl: string;
  startTime: number;
  duration: number;
}

export const JTB_VOICE_CLIPS: JtbVoiceClip[] = [
  {
    "seq": 1,
    "dimension": "基本学情",
    "caption": "哥哥：暑假前六年级、暑假后升初一；成绩一直 A，三科均衡。做小升初分班测数学习题，英语用百词斩，语文上高途网课（已学两年）。",
    "text": "针对小升初一个分班册的内容哦，",
    "clipUrl": "/clips/jiatingbao/user1/0001.mp3",
    "startTime": 429.6,
    "duration": 3.8
  },
  {
    "seq": 1,
    "dimension": "基本学情",
    "caption": "妹妹：暑假前三年级、升四年级；数学一直没进入状态，有 B/C；比较皮、只有英语打卡能坚持。",
    "text": "数学一直都没没没赶上，好像听不到。呃，没有没有进入状态哦，",
    "clipUrl": "/clips/jiatingbao/user1/0002.mp3",
    "startTime": 898.8,
    "duration": 8.9
  },
  {
    "seq": 1,
    "dimension": "基本学情",
    "caption": "家长最担心妹妹：怕数学基础没打好，五六年级更难搞。",
    "text": "到了到了五六年级就更难搞哦，",
    "clipUrl": "/clips/jiatingbao/user1/0003.mp3",
    "startTime": 990.5,
    "duration": 3.9
  },
  {
    "seq": 1,
    "dimension": "了解",
    "caption": "先下载 APP 了解，认为同步课（巩固基础）和培优课（家长认知是思维课）不错，思维课能锻炼孩子思维。",
    "text": "下载个 APP 先了解一下吗？",
    "clipUrl": "/clips/jiatingbao/user1/0004.mp3",
    "startTime": 1188.7,
    "duration": 2.6
  },
  {
    "seq": 1,
    "dimension": "了解",
    "caption": "思维培养和打基础可同时进行：先打基础，达到思维拓展更好，没达到再找私教。",
    "text": "达到他那个思维拓展的话，",
    "clipUrl": "/clips/jiatingbao/user1/0005.mp3",
    "startTime": 1566.8,
    "duration": 3.2
  },
  {
    "seq": 1,
    "dimension": "购买",
    "caption": "成交原因：2 个孩子都能顾及、有 90 天 1对1 服务、能衔接到高中、哥哥试用后三科都喜欢（尤其语文）。",
    "text": "因为嗯他他也有也好像有九十天的那一个一对一吧。",
    "clipUrl": "/clips/jiatingbao/user1/0006.mp3",
    "startTime": 1757.9,
    "duration": 6.5
  },
  {
    "seq": 1,
    "dimension": "预期",
    "caption": "一定用到高中毕业：预习（数学）；其他学科、AI 定制班买了也不亏；尽量让孩子用上思维课。",
    "text": "尽量尽量让孩子去用上，",
    "clipUrl": "/clips/jiatingbao/user1/0007.mp3",
    "startTime": 2253.1,
    "duration": 2.7
  },
  {
    "seq": 1,
    "dimension": "建议/反馈",
    "caption": "不买这个包也会买其他机构课；高途每天 2 小时太久，初中没时间。",
    "text": "这有一天每天两个小时一颗哦，",
    "clipUrl": "/clips/jiatingbao/user1/0008.mp3",
    "startTime": 2373.4,
    "duration": 3.9
  },
  {
    "seq": 2,
    "dimension": "基本学情",
    "caption": "老二七年级（年级前几名，近 2000 学生），主要靠超前学；自己安排好、基本不用管。",
    "text": "现在就是七年级了，马上不是七年级要完了，",
    "clipUrl": "/clips/jiatingbao/user2/0001.mp3",
    "startTime": 99.5,
    "duration": 3.5
  },
  {
    "seq": 2,
    "dimension": "基本学情",
    "caption": "数学已预习到 9 年级；英语在自学高中内容；准备暑假用洋葱提前学物理化学。",
    "text": "英语的话，他自己能力还是比较强，因为我自己也也是是我没有英语的，所以基本上可以辅导他嗯他的英语能力初衷是没有什么问题的。一开始呃上高中的学习了，应该他已经在自己自学高中的东西了，",
    "clipUrl": "/clips/jiatingbao/user2/0002.mp3",
    "startTime": 368.2,
    "duration": 17.9
  },
  {
    "seq": 2,
    "dimension": "基本学情",
    "caption": "小学语文拔尖，初中优势没发挥出来；生物地理较好，喜欢课外知识。",
    "text": "我感觉好像语文的优势没有发挥出来。",
    "clipUrl": "/clips/jiatingbao/user2/0003.mp3",
    "startTime": 636.4,
    "duration": 3.6
  },
  {
    "seq": 2,
    "dimension": "了解",
    "caption": "诉求：要超前学一些拔高、难一点的内容，不能只和学校同步。",
    "text": "那我们肯定不能跟学校同步的哦，",
    "clipUrl": "/clips/jiatingbao/user2/0004.mp3",
    "startTime": 930.5,
    "duration": 2.9
  },
  {
    "seq": 2,
    "dimension": "认知",
    "caption": "小孩自己发现的，看小红书上的意见后跟妈妈说。",
    "text": "他就是主要还是可能是看那些呃小红书上别人的意见啊。",
    "clipUrl": "/clips/jiatingbao/user2/0005.mp3",
    "startTime": 1034.3,
    "duration": 5.8
  },
  {
    "seq": 2,
    "dimension": "购买",
    "caption": "孩子要主动自学，需要有同步 + 提高/培优，由简入深、循序渐进。",
    "text": "我更看重的就是跟甲方一定要有同步啊。",
    "clipUrl": "/clips/jiatingbao/user2/0006.mp3",
    "startTime": 1059.1,
    "duration": 3.3
  },
  {
    "seq": 2,
    "dimension": "购买",
    "caption": "学习机本没打算买，销售建议买（杜绝平板分心、只能学习）；最开始只想买初中，要提前学就把高中也买了（家庭包），总价 9000 多元。",
    "text": "他比如说这个学习机嘛，本来我开始没有打算买学习机的。",
    "clipUrl": "/clips/jiatingbao/user2/0007.mp3",
    "startTime": 1201.0,
    "duration": 3.9
  },
  {
    "seq": 2,
    "dimension": "购买",
    "caption": "顾虑孩子会不会心血来潮、过段时间不学；因孩子自觉自律、说到做到，决定支持她、买到高中。",
    "text": "就是比如说有小孩子会不会是心血来潮啦？",
    "clipUrl": "/clips/jiatingbao/user2/0008.mp3",
    "startTime": 1412.3,
    "duration": 4.5
  },
  {
    "seq": 2,
    "dimension": "预期",
    "caption": "超前学能消化吸收，培养的知识能成体系（自己总结主线、串联知识）。",
    "text": "我希望他的他的意思就是说他能够呃能够超前学的东西，能够自己消化技术的话，",
    "clipUrl": "/clips/jiatingbao/user2/0009.mp3",
    "startTime": 1620.1,
    "duration": 8.7
  },
  {
    "seq": 2,
    "dimension": "预期",
    "caption": "不只是套公式，而是提高思维分析能力、培养自主思考与举一反三的能力。",
    "text": "希望的是更多的能够呃提高孩子那种思维分析能力，",
    "clipUrl": "/clips/jiatingbao/user2/0010.mp3",
    "startTime": 1758.7,
    "duration": 5.6
  },
  {
    "seq": 2,
    "dimension": "预期",
    "caption": "检验：遇到真实问题看孩子怎么解决、成绩有没有提升。算账「不考虑钱」，比 1对几培训班便宜。",
    "text": "他他他是说那肯定比学比上培训班要便宜点啊，",
    "clipUrl": "/clips/jiatingbao/user2/0011.mp3",
    "startTime": 2680.2,
    "duration": 4.7
  },
  {
    "seq": 2,
    "dimension": "关键原声",
    "caption": "既然要提前学就一起买，初中的时候就要往高中的时候学，不能等到了高中再学。",
    "text": "你要既然要学，因就是其实嗯你你既然要学嘛，你居然就要提前我们一起来。",
    "clipUrl": "/clips/jiatingbao/user2/0012.mp3",
    "startTime": 2821.1,
    "duration": 7.3
  },
  {
    "seq": 3,
    "dimension": "基本学情",
    "caption": "姐姐初三临近中考，七科都有，写作业磨蹭到 12 点；重点学校中等生，数学 120-130、理科偏弱（物理 58-61）。",
    "text": "姐姐肯定是比较忙的，因为临近中考了嘛，",
    "clipUrl": "/clips/jiatingbao/user3/0001.mp3",
    "startTime": 122.4,
    "duration": 3.6
  },
  {
    "seq": 3,
    "dimension": "基本学情",
    "caption": "妹妹四年级，三科作业一小时写完，练琴、读英语、洋葱复习；数学 98 左右、英语接近满分、语文弱。",
    "text": "要不然的话基本上三科的作业一个小时差不多哦，",
    "clipUrl": "/clips/jiatingbao/user3/0002.mp3",
    "startTime": 162.1,
    "duration": 4.5
  },
  {
    "seq": 3,
    "dimension": "基本学情",
    "caption": "最担心姐姐主动性不够；去年买的洋葱冲刺包姐姐不看，妹妹用得多。",
    "text": "其实这些都不是姐姐，姐姐让我比较担心。其实包括目前妹妹，其实慢慢的也有这样的一种表现，就是嗯嗯还是怎么讲，就是主动性不够，",
    "clipUrl": "/clips/jiatingbao/user3/0003.mp3",
    "startTime": 726.5,
    "duration": 11.0
  },
  {
    "seq": 3,
    "dimension": "了解",
    "caption": "之前买 4 年包（4000-5000 元），主要为姐姐中考，实际妹妹用得多。",
    "text": "然后当时就是因为姐姐马上要中考了，",
    "clipUrl": "/clips/jiatingbao/user3/0004.mp3",
    "startTime": 841.1,
    "duration": 2.7
  },
  {
    "seq": 3,
    "dimension": "关键原声",
    "caption": "姐姐上高中没精力管他了，会把更多精力放在小的身上。",
    "text": "因为尤其到了马上升到高中嘛，包括升到大学之后，其实我们之后慢慢就不可能再再管他了。",
    "clipUrl": "/clips/jiatingbao/user3/0005.mp3",
    "startTime": 900.7,
    "duration": 8.0
  },
  {
    "seq": 3,
    "dimension": "关键原声",
    "caption": "小升初的时候没有给报，现在想起来有点后悔。",
    "text": "那我那我因为他小小学升初中的时候，我我就我就怎么说呢？顶部的压力我没有给他保，",
    "clipUrl": "/clips/jiatingbao/user3/0006.mp3",
    "startTime": 1494.4,
    "duration": 8.2
  },
  {
    "seq": 3,
    "dimension": "购买",
    "caption": "家庭包首购触发：对接老师有活动时发消息，4 年只能保证姐姐高中毕业、妹妹达不到，刚好补到妹妹学到高中毕业。",
    "text": "就是我现在买的这个四年的话，只能保证几到高中哦，高中毕毕妹妹妹的话是是达不到的。嗯，然后所以当时她正好给我给我发了一个就是可以续报，就是呃什么全续六年的那种。嗯，然后就正好妹妹可以可以高中毕业。",
    "clipUrl": "/clips/jiatingbao/user3/0007.mp3",
    "startTime": 1975.3,
    "duration": 16.8
  },
  {
    "seq": 3,
    "dimension": "预期",
    "caption": "尽量不让妹妹补太多课，希望初中不补课，借助工具（洋葱、小红书）把学科学好、提前学。",
    "text": "就包括你小红书其实都都挺好的，对吧？因为里面有好多的那种博主啊或者干嘛他都有啊。对，就是嗯你要想真的你要自己想学的话，其实这些学习资料都是有的。所以我还是希望就是说我给你提供了这个东西，嗯，然后你可以自己借助这个东西，然后把这个学科学好，",
    "clipUrl": "/clips/jiatingbao/user3/0008.mp3",
    "startTime": 2039.4,
    "duration": 17.6
  },
  {
    "seq": 3,
    "dimension": "购买",
    "caption": "价格焦虑：去年价格低没买，后来涨价很多，吃过一次亏，这次先买。",
    "text": "就去年前一段时间应该是价格低很多的情况下，",
    "clipUrl": "/clips/jiatingbao/user3/0009.mp3",
    "startTime": 2127.4,
    "duration": 4.5
  },
  {
    "seq": 3,
    "dimension": "购买",
    "caption": "顾虑姐姐没看、妹妹会不会也这样；未打消但「该提供的提供到，实在不学也没办法」。续费最关注能否保证小宝高中毕业。",
    "text": "所以这个其实我也要考虑一下。我就在想那那妹妹会不会也出现这种问题呢？反正再观察四年嘛。",
    "clipUrl": "/clips/jiatingbao/user3/0010.mp3",
    "startTime": 2272.6,
    "duration": 5.9
  },
  {
    "seq": 3,
    "dimension": "使用",
    "caption": "给妹妹明确规划，AI 定制班规定每天干啥；寒暑假预习下学期、学期中主要复习。",
    "text": "啊然后既然就是说你这边已经 AI 定制班帮他规定好，",
    "clipUrl": "/clips/jiatingbao/user3/0011.mp3",
    "startTime": 2596.4,
    "duration": 4.7
  },
  {
    "seq": 3,
    "dimension": "建议/反馈",
    "caption": "《从小学物理》课包自带，妹妹很喜欢看；偏好「学科启蒙」，最终检测是中高考。",
    "text": "因为他们毕竟最终的最终检测还是中考高考，",
    "clipUrl": "/clips/jiatingbao/user3/0012.mp3",
    "startTime": 3091.4,
    "duration": 4.8
  },
  {
    "seq": 3,
    "dimension": "建议/反馈",
    "caption": "6 年级要把初中三年单词背完（更偏应试，PET 合肥不多，北上广更多）。",
    "text": "现在好多他们都嗯我们现在都说的是六年级，嗯，英语这块要把初中三年的单词全部背完。",
    "clipUrl": "/clips/jiatingbao/user3/0013.mp3",
    "startTime": 3193.6,
    "duration": 9.8
  },
  {
    "seq": 3,
    "dimension": "了解",
    "caption": "课程核心优势：同时有小初高内容（像图书馆），可按能力进入下一轮，还安排怎么学（AI 定制班）。",
    "text": "就是接受能力。嗯，他如果他他很快他把小学的已经看完了，嗯，当然他也他也都会啊，嗯呃就差不多都会嗯，然后他就可以进入下一轮了嘛，",
    "clipUrl": "/clips/jiatingbao/user3/0014.mp3",
    "startTime": 3320.9,
    "duration": 10.8
  },
  {
    "seq": 3,
    "dimension": "关键原声",
    "caption": "不需要接送，孩子也不用赶路，时间成本也没有，还比私教班便宜，私教班一门就一万多。",
    "text": "时间成本也没有哦，",
    "clipUrl": "/clips/jiatingbao/user3/0015.mp3",
    "startTime": 4118.4,
    "duration": 2.2
  },
  {
    "seq": 4,
    "dimension": "基本学情",
    "caption": "姐姐 6 年级，学游泳每周 6 次占用大量时间，暑假想提前学初中；各科 95 分以上，但非冒尖型，家长希望培养内驱力。",
    "text": "嗯呃想在这个暑假的时候呢嗯利用这些学习资源呢嗯呃让他提前学习一下。然后这个到正式进入初中，",
    "clipUrl": "/clips/jiatingbao/user4/0001.mp3",
    "startTime": 690.6,
    "duration": 14.8
  },
  {
    "seq": 4,
    "dimension": "基本学情",
    "caption": "弟弟 1 年级，数学语文课内预复习、计算练习；课内成绩跟得上，对数字较强。",
    "text": "然后就就数学语文的课内的嗯复习预习嗯，",
    "clipUrl": "/clips/jiatingbao/user4/0002.mp3",
    "startTime": 1172.6,
    "duration": 7.5
  },
  {
    "seq": 4,
    "dimension": "基本学情",
    "caption": "更担心姐姐（马上上初中）；担心孩子看答案、不会自主思考，但家长也不知道怎么办。",
    "text": "嗯也不知道怎么指导孩子去把握这个度。",
    "clipUrl": "/clips/jiatingbao/user4/0003.mp3",
    "startTime": 1588.2,
    "duration": 3.7
  },
  {
    "seq": 4,
    "dimension": "购买",
    "caption": "没有具体学习问题，只因博主介绍、想提前准备；7000 多元、知道是 6 年。",
    "text": "没有嗯没有具体的学习问题，",
    "clipUrl": "/clips/jiatingbao/user4/0004.mp3",
    "startTime": 2114.1,
    "duration": 3.1
  },
  {
    "seq": 4,
    "dimension": "使用",
    "caption": "打算调整学习时间，先准备好内容；小的用得多、大的也在用；希望 2 个孩子一起用、发挥最大功效。",
    "text": "那个可以一起的那可以两个一起用，",
    "clipUrl": "/clips/jiatingbao/user4/0005.mp3",
    "startTime": 2228.1,
    "duration": 4.6
  },
  {
    "seq": 4,
    "dimension": "关键原声",
    "caption": "希望 2 个孩子一起用，账号不会相互冲突，希望能发挥到最大的功效。",
    "text": "然后分了两个账号也不会相互冲突，",
    "clipUrl": "/clips/jiatingbao/user4/0006.mp3",
    "startTime": 2232.2,
    "duration": 3.9
  },
  {
    "seq": 4,
    "dimension": "关键原声",
    "caption": "阿刘教育规划训练营……只是单纯说这个好、提供链接，从客观公正的角度说，比起销售更相信他。",
    "text": "对吧？如果我只是单独的说你这个东西好，嗯，",
    "clipUrl": "/clips/jiatingbao/user4/0007.mp3",
    "startTime": 2789.5,
    "duration": 4.5
  },
  {
    "seq": 4,
    "dimension": "了解",
    "caption": "直播间已确定课程内容，不信销售（王婆卖瓜），更信第三方博主。",
    "text": "这个那你你肯定说自己家的王婆卖瓜嘛，",
    "clipUrl": "/clips/jiatingbao/user4/0008.mp3",
    "startTime": 2912.3,
    "duration": 4.0
  },
  {
    "seq": 4,
    "dimension": "购买",
    "caption": "具体关注：2 个小孩能不能一起用；顾虑用不好能否退。",
    "text": "就是两个小孩能不能一起用嘛？",
    "clipUrl": "/clips/jiatingbao/user4/0009.mp3",
    "startTime": 2986.6,
    "duration": 4.4
  },
  {
    "seq": 5,
    "dimension": "了解",
    "caption": "让孩子体验过、孩子喜欢才买；销售说什么课都有、时间长。",
    "text": "什么课都有嘛，",
    "clipUrl": "/clips/jiatingbao/user5/0001.mp3",
    "startTime": 1103.2,
    "duration": 1.5
  },
  {
    "seq": 5,
    "dimension": "购买",
    "caption": "顾虑：线下有无门店、会不会倒闭、课程更新是否及时、孩子会不会看一会就不看。",
    "text": "其他的就怕你到时候你课程更新啊什么的，嗯，会不会及时啊什么？",
    "clipUrl": "/clips/jiatingbao/user5/0002.mp3",
    "startTime": 1149.6,
    "duration": 5.3
  },
  {
    "seq": 5,
    "dimension": "关键原声",
    "caption": "买小学+初中的会有浪费，反而还有 1 年不够用。",
    "text": "我买小学的话用不了多久？我买小学到初中的话，感觉还会有浪费。",
    "clipUrl": "/clips/jiatingbao/user5/0003.mp3",
    "startTime": 1225.6,
    "duration": 5.3
  },
  {
    "seq": 5,
    "dimension": "基本学情",
    "caption": "弟弟 5 年级：买过「一起作业」（上课 2 小时太久、视力变差）；中等偏上，英语弱（80 左右）、数学 80-90，无突出学科。",
    "text": "买过一个一起作业的那个啊，",
    "clipUrl": "/clips/jiatingbao/user5/0004.mp3",
    "startTime": 1438.8,
    "duration": 2.6
  },
  {
    "seq": 5,
    "dimension": "关键原声",
    "caption": "以后会价格更贵，因为套餐分开买更贵。",
    "text": "你们那个套餐不是分开买正贵吗？",
    "clipUrl": "/clips/jiatingbao/user5/0005.mp3",
    "startTime": 2114.3,
    "duration": 3.0
  },
  {
    "seq": 5,
    "dimension": "建议/反馈",
    "caption": "推荐给 2 个不同年级孩子，1 个孩子不划算；可提前学、自己安排课、上课灵活。",
    "text": "一个孩子的话就不是很划算了。",
    "clipUrl": "/clips/jiatingbao/user5/0006.mp3",
    "startTime": 2249.7,
    "duration": 2.7
  },
  {
    "seq": 6,
    "dimension": "建议/反馈",
    "caption": "有效果才会推荐；2 个孩子都在用、总时长汇总在一起，希望能单独区分。",
    "text": "对他因为一个账号里相当于两个人都在用了哦啊，",
    "clipUrl": "/clips/jiatingbao/user6/0001.mp3",
    "startTime": 323.6,
    "duration": 6.7
  },
  {
    "seq": 6,
    "dimension": "购买",
    "caption": "5000 多元，送的学习机折现便宜了 1700 元；最主要目的是提前学。",
    "text": "那你这边的主要目的是什么？",
    "clipUrl": "/clips/jiatingbao/user6/0002.mp3",
    "startTime": 394.0,
    "duration": 2.1
  },
  {
    "seq": 6,
    "dimension": "关键原声",
    "caption": "花这么多钱不一定能见到提分效果。",
    "text": "花这么多不一定见到效果吧，",
    "clipUrl": "/clips/jiatingbao/user6/0003.mp3",
    "startTime": 781.7,
    "duration": 2.2
  },
  {
    "seq": 6,
    "dimension": "基本学情",
    "caption": "认为学而思也是看视频、和洋葱没大区别，还是看主观能动性（打 3 分）。",
    "text": "有些线下的也是去看视频哦，",
    "clipUrl": "/clips/jiatingbao/user6/0004.mp3",
    "startTime": 1146.0,
    "duration": 3.6
  },
  {
    "seq": 6,
    "dimension": "认知",
    "caption": "刷抖音刷到，说数学比较好；也了解到名师单独授课，没对比过竞品。",
    "text": "带有那种是我看那个抖音上面那种也是证名师啊嗯单独授授课啊。",
    "clipUrl": "/clips/jiatingbao/user6/0005.mp3",
    "startTime": 1575.5,
    "duration": 6.3
  },
  {
    "seq": 6,
    "dimension": "关键原声",
    "caption": "学而思形式也看视频，和洋葱没有太大区别，都是看视频，还是看主观能动性。",
    "text": "怎么可能他们也觉得这个差别形式其实也没有太大区别吧。",
    "clipUrl": "/clips/jiatingbao/user6/0006.mp3",
    "startTime": 1674.6,
    "duration": 5.3
  },
  {
    "seq": 6,
    "dimension": "关键原声",
    "caption": "想等有效果才买（高中的），数学要至少到 90 分以上。",
    "text": "当时的数学能到都到九十分以上了，",
    "clipUrl": "/clips/jiatingbao/user6/0007.mp3",
    "startTime": 1714.9,
    "duration": 2.9
  },
  {
    "seq": 7,
    "dimension": "基本学情",
    "caption": "高一孩子：成绩不大好，班里排名见底；普通班一年级 400 多人，去年期末 300 多名。",
    "text": "去年去年期末是三百多年哦，三百三百，那么三百五十多还是三百二的米。",
    "clipUrl": "/clips/jiatingbao/user7/0001.mp3",
    "startTime": 211.2,
    "duration": 7.6
  },
  {
    "seq": 7,
    "dimension": "基本学情",
    "caption": "自家还有个四年级孩子，不爱看洋葱（觉得基础，雪球都看过了）。",
    "text": "因为我这里有个小的小孩子四年级才班，",
    "clipUrl": "/clips/jiatingbao/user7/0002.mp3",
    "startTime": 377.7,
    "duration": 3.3
  },
  {
    "seq": 7,
    "dimension": "预期",
    "caption": "担心没效果——看摸底成绩反馈；效果体现在学习方法改变、学懂底层知识点、信心出来。",
    "text": "先先先解释底层逻辑是什么，让小孩更理解这个这个知识点。",
    "clipUrl": "/clips/jiatingbao/user7/0003.mp3",
    "startTime": 599.3,
    "duration": 4.4
  },
  {
    "seq": 7,
    "dimension": "关键原声",
    "caption": "将一个抽象的东西具体化，对孩子理解好。",
    "text": "因为你你把那个一个抽象的东西具体具体化，",
    "clipUrl": "/clips/jiatingbao/user7/0004.mp3",
    "startTime": 758.7,
    "duration": 3.9
  },
  {
    "seq": 7,
    "dimension": "认知",
    "caption": "搜索千问问「数学 AI 动画比较好的」，先推荐了欧拉和洋葱；试过欧拉觉得有缺陷。",
    "text": "我觉得刚开始欧拉觉得挺好的。嗯，哎后来我就是后来我老婆也试了，我来她，后来她跟我解了什么原因呢？嗯，然后这个是四蕾延窗，我就我就就没我就没搞懂，我我我给忘记了。嗯，但是他对你刚跟我说欧拉有什么缺陷之类的，",
    "clipUrl": "/clips/jiatingbao/user7/0005.mp3",
    "startTime": 930.9,
    "duration": 16.7
  },
  {
    "seq": 7,
    "dimension": "了解",
    "caption": "体验洋葱同步课 + 培优，重点关注动画；风格好、不粗糙、孩子感兴趣、能把抽象知识点讲出来。",
    "text": "看那个你们同步课同步课程的那个动画，我去看了一下，我觉得还可以。嗯嗯，唉对，然后培优的我我自己也进去看，",
    "clipUrl": "/clips/jiatingbao/user7/0006.mp3",
    "startTime": 1065.2,
    "duration": 8.8
  },
  {
    "seq": 7,
    "dimension": "关键原声",
    "caption": "风格好，不粗糙，孩子感兴趣，抽象的知识点能讲解出来。",
    "text": "然后另外一个就是那个就是复杂的一些知识点，能够用动画形象的给它描述出来，",
    "clipUrl": "/clips/jiatingbao/user7/0007.mp3",
    "startTime": 1124.5,
    "duration": 7.2
  },
  {
    "seq": 7,
    "dimension": "购买",
    "caption": "购买前主动问老师体验，给了 3 天体验权益；先介绍 4k 多课程，主动问一大一小有没有便宜的，推荐了 7k 套餐。",
    "text": "就是一大一小嘛，本来我想给老二也弄一个，我说一大小的有没有更便宜一点，",
    "clipUrl": "/clips/jiatingbao/user7/0008.mp3",
    "startTime": 1349.2,
    "duration": 5.1
  },
  {
    "seq": 7,
    "dimension": "购买",
    "caption": "课程可学 6 年（本来高中只能学两年）。",
    "text": "看六点六年是吧，对不对？这个是家庭班，是六年的，本来高中的时候是两年的。",
    "clipUrl": "/clips/jiatingbao/user7/0009.mp3",
    "startTime": 1750.8,
    "duration": 8.3
  },
  {
    "seq": 7,
    "dimension": "关键原声",
    "caption": "看着看着没兴趣——这个更重要，买了不看再好也没用。",
    "text": "这边就买了东西，他不看你再好东西也没用嘛，",
    "clipUrl": "/clips/jiatingbao/user7/0010.mp3",
    "startTime": 1888.8,
    "duration": 4.2
  },
  {
    "seq": 7,
    "dimension": "使用",
    "caption": "孩子周末自己挑着学；暑假打算全面补充、主要复习，也提前学一点高二，针对理科。",
    "text": "复习复复习先复习前在发话的时候提前学一点吧。",
    "clipUrl": "/clips/jiatingbao/user7/0011.mp3",
    "startTime": 2301.2,
    "duration": 4.3
  },
  {
    "seq": 7,
    "dimension": "建议/反馈",
    "caption": "做错的题和拍照的题可以放一起；讲逻辑和做 AI 的可以多一点，把知识点更形象展现。",
    "text": "就是就是这些简逻辑的那种 AI 的 b 就是包括这些方面可以再做多做的多一点。",
    "clipUrl": "/clips/jiatingbao/user7/0012.mp3",
    "startTime": 2502.9,
    "duration": 8.6
  },
  {
    "seq": 8,
    "dimension": "基本学情",
    "caption": "老二（六年级升七）：各科较均衡 90 多分，阅读量不够；右脑发育不如左脑，担心升初一像老大。",
    "text": "嗯然后他的右脑发育也是没有左脑好的，",
    "clipUrl": "/clips/jiatingbao/user8/0001.mp3",
    "startTime": 325.4,
    "duration": 5.1
  },
  {
    "seq": 8,
    "dimension": "了解",
    "caption": "关键转化点：老大试听学而思数学不满意（像老师讲课、一节 1.5 小时），改试听洋葱，被 PK 等做题玩法吸引。",
    "text": "所以我给他报了学而思的数学的了哦，在他报了之后呢，他上了一两节课呢，他觉得不行。嗯嗯，他反正有抵触心理，就像他了。呃，老师讲课的一样的感觉就是可能比老师讲的细吧，",
    "clipUrl": "/clips/jiatingbao/user8/0002.mp3",
    "startTime": 1210.7,
    "duration": 18.4
  },
  {
    "seq": 8,
    "dimension": "基本学情",
    "caption": "老大（七年级，最担心）：语文英语好、数学最大短板；偏科严重（数学/历史/生物/地理 60 多分）；内向被动、有难题不敢问老师。",
    "text": "他就是有难题，有不懂的，他不敢问老师啊，",
    "clipUrl": "/clips/jiatingbao/user8/0003.mp3",
    "startTime": 1468.9,
    "duration": 4.1
  },
  {
    "seq": 8,
    "dimension": "认知",
    "caption": "自己和孩子看完都没感觉、不看好；后来刷到阿刘规划，评论多次提到洋葱，加群咨询。",
    "text": "然后评论里面啊也有一些呃提到洋葱啊。",
    "clipUrl": "/clips/jiatingbao/user8/0004.mp3",
    "startTime": 1622.2,
    "duration": 3.8
  },
  {
    "seq": 8,
    "dimension": "认知",
    "caption": "第一次听说来自女儿同学的家长「数学不用报班，丢个洋葱在家看就行」，把整套视频发给她。",
    "text": "丢个洋葱给他在家看就行了。",
    "clipUrl": "/clips/jiatingbao/user8/0005.mp3",
    "startTime": 1649.5,
    "duration": 2.3
  },
  {
    "seq": 8,
    "dimension": "关键原声",
    "caption": "他丢个文件夹给你点开看，跟报了课看的感觉不一样……没有输出就是盲目接收。",
    "text": "然后那一种他丢了一个包，一个文件夹过来给你，你可以点开看呢，",
    "clipUrl": "/clips/jiatingbao/user8/0006.mp3",
    "startTime": 1736.0,
    "duration": 6.3
  },
  {
    "seq": 8,
    "dimension": "购买",
    "caption": "直接买最长 6 年（到高中）：6 年里大宝二宝用完、三宝用到中考、老四用到五年级；没问孩子能否坚持，果断决定。",
    "text": "你他他就说你如果买六年年限的话呢，你你的大宝二保都可以用完了。",
    "clipUrl": "/clips/jiatingbao/user8/0007.mp3",
    "startTime": 2186.0,
    "duration": 6.7
  },
  {
    "seq": 8,
    "dimension": "使用",
    "caption": "主要使用者老大、老二（跟 1对1 老师定的 AI 定制班学习）；老三顺带、老四未来。",
    "text": "我也不知道他用哪些是洋聪的那个一对一那个老师帮我制定的那个 AI 班里面的哦 AI 定制班，",
    "clipUrl": "/clips/jiatingbao/user8/0008.mp3",
    "startTime": 2369.6,
    "duration": 8.0
  },
  {
    "seq": 8,
    "dimension": "使用",
    "caption": "已绑定家庭组（爸爸管初中、妈妈管小学），实现学情报告分开看。",
    "text": "然后呃老师呢就说那那加入家庭组，然后就把初中和小学的，我就建议把它这两组分开。因为现在老三不怎么用嘛。嗯那我把小学初中分开的一个爸爸管一个妈妈管的账号的话，",
    "clipUrl": "/clips/jiatingbao/user8/0009.mp3",
    "startTime": 2625.3,
    "duration": 14.6
  },
  {
    "seq": 8,
    "dimension": "关键原声",
    "caption": "如果有效果，我会排除万难让他们学下去。",
    "text": "我觉得如果有效果，我会排除万难，让他们学下去。",
    "clipUrl": "/clips/jiatingbao/user8/0010.mp3",
    "startTime": 2772.3,
    "duration": 4.9
  },
  {
    "seq": 8,
    "dimension": "预期",
    "caption": "老大数学学到 108 分以上就值了；认同考试是跨学科、非题海，希望文科有更多拓展。",
    "text": "我觉得能把他数学学到一百零八分以上也值了哦，",
    "clipUrl": "/clips/jiatingbao/user8/0011.mp3",
    "startTime": 3043.8,
    "duration": 4.8
  },
  {
    "seq": 8,
    "dimension": "建议/反馈",
    "caption": "学情报告按孩子拆分；推荐时用自己孩子讲「闭环学习」，建议年龄跨度大的家庭直接买 6 年。",
    "text": "但是如果说我孩子期末考试他进步很大的话，人家肯定会问我嘛。嗯，他就说他他反正这一个月他都在家没有去自习，就是在家上洋葱。嗯嗯，普通呢他就是一个闭环学习，",
    "clipUrl": "/clips/jiatingbao/user8/0012.mp3",
    "startTime": 3258.8,
    "duration": 15.6
  },
  {
    "seq": 8,
    "dimension": "关键原声",
    "caption": "几个孩子同时在房间学完，就能一起出发……我孩子多就会想到这些。",
    "text": "你你三个孩子同时在自己的房间学完了，",
    "clipUrl": "/clips/jiatingbao/user8/0013.mp3",
    "startTime": 3497.5,
    "duration": 3.1
  },
  {
    "seq": 10,
    "dimension": "基本学情",
    "caption": "初一男孩：作业多且耗时，晚上 10 点半左右写完；排名 30 左右，中等水平；数学薄弱，线下数学班 1 对 5 / 2 小时，目前从寒假开始上但没明显起色。",
    "text": "他现在的作业时间是晚上到十点半，是比较普遍的情况哦。小学七年级嗯就很好，他这边基本上八点半左右，",
    "clipUrl": "/clips/jiatingbao/user10/0001.mp3",
    "startTime": 484.2,
    "duration": 11.8
  },
  {
    "seq": 10,
    "dimension": "基本学情",
    "caption": "家长复盘老大踩坑：快乐教育、读书认字培养太晚，导致一年级识字量跟不上；数学思维和应用题理解也受阅读能力影响。",
    "text": "就是当时就是就没有刻意的去培养他的这这种这个读书认字啊，嗯就是阅读习惯培养的太晚了。",
    "clipUrl": "/clips/jiatingbao/user10/0002.mp3",
    "startTime": 1070.1,
    "duration": 9.2
  },
  {
    "seq": 10,
    "dimension": "基本学情",
    "caption": "四年级孩子：作业晚上七点半完成，成绩不错，家长从来不担心；从小加强绘本阅读、识字和学习习惯。",
    "text": "但是在这个嗯绘本阅读上也不算晚开始的。",
    "clipUrl": "/clips/jiatingbao/user10/0003.mp3",
    "startTime": 1098.6,
    "duration": 6.2
  },
  {
    "seq": 10,
    "dimension": "认知",
    "caption": "几年前了解过洋葱，但因为视力问题放弃；这次想安排暑期学习计划，通过豆包了解线上课程体系。",
    "text": "呃只是因为视力的问题，",
    "clipUrl": "/clips/jiatingbao/user10/0004.mp3",
    "startTime": 2088.9,
    "duration": 2.4
  },
  {
    "seq": 10,
    "dimension": "认知",
    "caption": "原本想给老大补空，登录 APP 后发现有小学内容，老二看了非常喜欢。",
    "text": "然后就那个让老二看了看，嗯嗯，然后老二觉得还挺好玩的。嗯，然后我们就反而是买了一那个试听课嘛。嗯，老大没有时间试听，因为写的对太晚了，老二就天天喜欢去听一节两节的，",
    "clipUrl": "/clips/jiatingbao/user10/0005.mp3",
    "startTime": 2140.2,
    "duration": 15.7
  },
  {
    "seq": 10,
    "dimension": "了解",
    "caption": "认为洋葱适合线下课前预习和日常补空，每节课知识点拆得细、短而有趣。",
    "text": "是因为它每一节课每一个点，每一个知识点它拆的非常的细。",
    "clipUrl": "/clips/jiatingbao/user10/0006.mp3",
    "startTime": 2329.8,
    "duration": 5.5
  },
  {
    "seq": 10,
    "dimension": "购买",
    "caption": "一开始为了数学，后来试用 7 天全科包后，老二不仅看小学内容，也对初中物理、生物感兴趣，强化了全科家庭包“买了会用、不浪费”的判断。",
    "text": "正规的数学是为了一开始接触洋葱，是为了数学。",
    "clipUrl": "/clips/jiatingbao/user10/0007.mp3",
    "startTime": 2386.0,
    "duration": 4.8
  },
  {
    "seq": 10,
    "dimension": "关键原声",
    "caption": "先在洋葱上学习一下，在上线下课之前，用洋葱先预习一下。觉得比直接上线下课效果好。",
    "text": "我觉得在上线下课之前，",
    "clipUrl": "/clips/jiatingbao/user10/0008.mp3",
    "startTime": 3068.0,
    "duration": 2.6
  },
  {
    "seq": 10,
    "dimension": "了解",
    "caption": "没法完全替代线下课：依赖孩子自觉性，且需要有人或模块把拆开的知识点串起来。",
    "text": "我觉得他可能还是嗯他依赖于孩子的这种自觉性吧，",
    "clipUrl": "/clips/jiatingbao/user10/0009.mp3",
    "startTime": 3224.9,
    "duration": 9.2
  },
  {
    "seq": 10,
    "dimension": "使用",
    "caption": "家长期待孩子每天都能上一下感兴趣的内容，老大至少把课程过一遍，老二把五年级课程顺一遍。",
    "text": "比如说我我我老大，我可能暑假会让他完成。对，下学期就是每这个这个知识点的一个初步预习。嗯，呃至少把这个课啊，他这个觉得这个什么的先给他过一遍。",
    "clipUrl": "/clips/jiatingbao/user10/0010.mp3",
    "startTime": 3404.3,
    "duration": 14.5
  },
  {
    "seq": 10,
    "dimension": "关键原声",
    "caption": "孩子只要喜欢用，就满足了自己的购买预期。感兴趣就都可以看。",
    "text": "对我觉得只要孩子喜欢用，",
    "clipUrl": "/clips/jiatingbao/user10/0011.mp3",
    "startTime": 3453.3,
    "duration": 2.6
  },
  {
    "seq": 10,
    "dimension": "预期",
    "caption": "只要孩子感兴趣、每天能上能用，就不浪费；老二兴趣是购买家庭包的重要确定性。",
    "text": "那你要说最明显的效果肯定是对于老大这种普通孩子，他提个提上一点分数进步了，这就是效果。对于老二来讲，我觉得他只要感兴趣，",
    "clipUrl": "/clips/jiatingbao/user10/0012.mp3",
    "startTime": 3766.5,
    "duration": 10.9
  },
  {
    "seq": 10,
    "dimension": "建议/反馈",
    "caption": "预习场景下题量不够，特别是数学需要更多配套练习。",
    "text": "但是预习阶段的题量不够，",
    "clipUrl": "/clips/jiatingbao/user10/0013.mp3",
    "startTime": 4696.1,
    "duration": 3.4
  },
  {
    "seq": 10,
    "dimension": "建议/反馈",
    "caption": "家长提出 AI 实体答疑产品机会：可爱造型、无需手机拍照、支持语音问答/讲故事/十万个为什么，价格预期约 100-150 元。",
    "text": "就是就充当一个十万个为什么，",
    "clipUrl": "/clips/jiatingbao/user10/0014.mp3",
    "startTime": 5261.0,
    "duration": 3.0
  }
];
