// Auto-generated by jiatingbao_slicer.py — 家庭包逐字原声切片（按维度）
export interface JtbVoiceClip {
  seq: number;
  dimension: string;
  caption: string;
  text: string;
  clipUrl: string;
  startTime: number;
  duration: number;
}

export const JTB_VOICE_CLIPS: JtbVoiceClip[] = [
  {
    "seq": 1,
    "dimension": "关键原声",
    "caption": "怕数学基础没打好，五六年级会更难搞。",
    "text": "是怕基础没打好。到了到了五六年级就更难搞哦，",
    "clipUrl": "/clips/jiatingbao/user1/0001.mp3",
    "startTime": 988.9,
    "duration": 5.3
  },
  {
    "seq": 1,
    "dimension": "购买",
    "caption": "担忧买了浪费、孩子不能坚持；最终打消是因为哥哥自己说喜欢学。",
    "text": "他买了浪费，就是怕孩子不能坚持。对，想因为我呃哥哥一直都是上直播课，他嗯比较喜欢跟老师互动的哦，",
    "clipUrl": "/clips/jiatingbao/user1/0002.mp3",
    "startTime": 2031.0,
    "duration": 12.4
  },
  {
    "seq": 2,
    "dimension": "基本学情",
    "caption": "小学语文拔尖，初中优势没发挥出来；生物地理较好，喜欢课外知识。",
    "text": "七年级的时候他小学的语文还是蛮拔尖的。嗯，但是到了初中，我感觉好像语文的优势没有发挥出来。",
    "clipUrl": "/clips/jiatingbao/user2/0001.mp3",
    "startTime": 631.3,
    "duration": 8.5
  },
  {
    "seq": 2,
    "dimension": "了解",
    "caption": "爸爸看了几天、在洋葱里比较是否适合；认为洋葱最强是数学（前身洋葱数学）。",
    "text": "他爸爸呃看了一下，考虑了几天比较了一下，是跟哪几个品牌比较了下，还是说在洋葱里边不同的产品里边比较了一下是哪一种？应该是说主要就是看杨崇学，",
    "clipUrl": "/clips/jiatingbao/user2/0002.mp3",
    "startTime": 801.9,
    "duration": 13.7
  },
  {
    "seq": 2,
    "dimension": "了解",
    "caption": "诉求：要超前学一些拔高、难一点的内容，不能只和学校同步。",
    "text": "嗯可能在课堂里面他拔高超前的可能就比较少一点了。嗯，像我们学生成绩比较，我们还成绩比较好的，那我们肯定不能跟学校同步的哦，",
    "clipUrl": "/clips/jiatingbao/user2/0003.mp3",
    "startTime": 923.8,
    "duration": 9.5
  },
  {
    "seq": 2,
    "dimension": "预期",
    "caption": "超前学能消化吸收，培养的知识能成体系（自己总结主线、串联知识）。",
    "text": "我希望他的他的意思就是说他能够呃能够超前学的东西，能够自己消化技术的话，那再能够他能够达到那个他呃培知识成体系嘛，",
    "clipUrl": "/clips/jiatingbao/user2/0004.mp3",
    "startTime": 1620.2,
    "duration": 12.7
  },
  {
    "seq": 2,
    "dimension": "关键原声",
    "caption": "不只是教孩子套什么公式、教你怎么解题，而是要提高孩子的思维分析能力。",
    "text": "套什么公式嗯，这样去做。嗯，希望的是更多的能够呃提高孩子那种思维分析能力，嗯，学会如何去解决问题，",
    "clipUrl": "/clips/jiatingbao/user2/0005.mp3",
    "startTime": 1756.4,
    "duration": 10.5
  },
  {
    "seq": 2,
    "dimension": "预期",
    "caption": "不只是套公式，而是提高思维分析能力、培养自主思考与举一反三的能力。",
    "text": "他就不知道怎么做了。哦，换一种就是最好是就是要培养孩子你套自主学习呃，去思考这个问题能力，提高他的思维能力。我觉得这这个是更好的嗯思维能力，",
    "clipUrl": "/clips/jiatingbao/user2/0006.mp3",
    "startTime": 1780.5,
    "duration": 14.0
  },
  {
    "seq": 2,
    "dimension": "关键原声",
    "caption": "既然要提前学就一起买，初中的时候就要往高中的时候学，不能等到了高中再学。",
    "text": "初中就要我们高中的学量，那肯定的啊。哦哦，那肯定不能等到了高中再学啊。",
    "clipUrl": "/clips/jiatingbao/user2/0007.mp3",
    "startTime": 2848.6,
    "duration": 6.3
  },
  {
    "seq": 3,
    "dimension": "关键原声",
    "caption": "小升初的时候没有给报，现在想起来有点后悔。",
    "text": "那我那我因为他小小学升初中的时候，我我就我就怎么说呢？顶部的压力我没有给他保，嗯，但是可能现在觉得会有点后悔吧。",
    "clipUrl": "/clips/jiatingbao/user3/0001.mp3",
    "startTime": 1494.5,
    "duration": 11.5
  },
  {
    "seq": 3,
    "dimension": "购买",
    "caption": "价格焦虑：去年价格低没买，后来涨价很多，吃过一次亏，这次先买。",
    "text": "就去年前一段时间应该是价格低很多的情况下，嗯，然后嗯当时没有买，然后后来就发现他忽然间真呃他真的涨价涨了很多。",
    "clipUrl": "/clips/jiatingbao/user3/0002.mp3",
    "startTime": 2127.4,
    "duration": 11.9
  },
  {
    "seq": 3,
    "dimension": "关键原声",
    "caption": "姐姐上高中没精力管他了，会把更多精力放在小的身上。",
    "text": "啊马上姐姐呃，就是读高中了以后，应该我我们就管不了他了。嗯，呃也不知道他会住校还是干嘛，但是大部分精力应该就会放小身上，",
    "clipUrl": "/clips/jiatingbao/user3/0003.mp3",
    "startTime": 2725.5,
    "duration": 8.9
  },
  {
    "seq": 3,
    "dimension": "关键原声",
    "caption": "不需要接送，孩子也不用赶路，时间成本也没有，还比私教班便宜，私教班一门就一万多。",
    "text": "肯定比那个补课要便宜多了呀。我还不需要接送，时间成本也没有哦，就路费也没有，",
    "clipUrl": "/clips/jiatingbao/user3/0004.mp3",
    "startTime": 4115.2,
    "duration": 6.9
  },
  {
    "seq": 4,
    "dimension": "关键原声",
    "caption": "希望 2 个孩子一起用，账号不会相互冲突，希望能发挥到最大的功效。",
    "text": "那个可以一起的那可以两个一起用，然后分了两个账号也不会相互冲突，",
    "clipUrl": "/clips/jiatingbao/user4/0001.mp3",
    "startTime": 2228.1,
    "duration": 7.8
  },
  {
    "seq": 4,
    "dimension": "关键原声",
    "caption": "如果 2 个不能同时用，就不考虑了。",
    "text": "但是我有个大的，我可能不能用，那我我可能就会考虑哦，",
    "clipUrl": "/clips/jiatingbao/user4/0002.mp3",
    "startTime": 2608.1,
    "duration": 5.4
  },
  {
    "seq": 5,
    "dimension": "关键原声",
    "caption": "买小学+初中的会有浪费，反而还有 1 年不够用。",
    "text": "我买小学的话用不了多久？嗯，我买小学到初中的话，感觉还会有浪费。",
    "clipUrl": "/clips/jiatingbao/user5/0001.mp3",
    "startTime": 1225.7,
    "duration": 5.1
  },
  {
    "seq": 5,
    "dimension": "了解",
    "caption": "让孩子体验过、孩子喜欢才买；销售说什么课都有、时间长。",
    "text": "有让他看过一下，他说喜欢的呀嗯就孩子体验过，体验完之后孩子觉得喜欢你才买的。",
    "clipUrl": "/clips/jiatingbao/user5/0002.mp3",
    "startTime": 1382.4,
    "duration": 7.5
  },
  {
    "seq": 5,
    "dimension": "关键原声",
    "caption": "现在先学 5 年级内容复习，寒暑假预习 6 年级内容。",
    "text": "ok 每个学科都是上他现在目前学的是已经在学六年级内容了，还是在复习五年级内容。",
    "clipUrl": "/clips/jiatingbao/user5/0003.mp3",
    "startTime": 1882.2,
    "duration": 6.0
  },
  {
    "seq": 5,
    "dimension": "关键原声",
    "caption": "以后会价格更贵，因为套餐分开买更贵。",
    "text": "那个套餐分开买更贵哦，",
    "clipUrl": "/clips/jiatingbao/user5/0004.mp3",
    "startTime": 2117.9,
    "duration": 2.6
  },
  {
    "seq": 7,
    "dimension": "关键原声",
    "caption": "将一个抽象的东西具体化，对孩子理解好。",
    "text": "因为你你把那个一个抽象的东西具体具体化，就对小孩的理解类似有帮助的哦，",
    "clipUrl": "/clips/jiatingbao/user7/0001.mp3",
    "startTime": 758.8,
    "duration": 6.4
  },
  {
    "seq": 7,
    "dimension": "购买",
    "caption": "课程可学 6 年（本来高中只能学两年）。",
    "text": "是六年的，本来高中的时候是两年的。嗯，后来说就就多了几千块钱，可以学六年还多一个小孩嘛，",
    "clipUrl": "/clips/jiatingbao/user7/0002.mp3",
    "startTime": 1756.1,
    "duration": 6.4
  },
  {
    "seq": 7,
    "dimension": "关键原声",
    "caption": "看着看着没兴趣——这个更重要，买了不看再好也没用。",
    "text": "效果都有点这个更更重要嘛。嗯嗯嗯嗯，或者没兴趣学了。对，这边就买了东西，他不看你再好东西也没用嘛，",
    "clipUrl": "/clips/jiatingbao/user7/0003.mp3",
    "startTime": 1884.4,
    "duration": 8.4
  },
  {
    "seq": 8,
    "dimension": "关键原声",
    "caption": "他丢个文件夹给你点开看，跟报了课看的感觉不一样……没有输出就是盲目接收。",
    "text": "然后那一种他丢了一个包，一个文件夹过来给你，你可以点开看呢，你有感觉就跟我报了课之后，看的感觉也不一样。",
    "clipUrl": "/clips/jiatingbao/user8/0001.mp3",
    "startTime": 1736.1,
    "duration": 10.3
  },
  {
    "seq": 8,
    "dimension": "预期",
    "caption": "暂以期末考试结果作为短期验证。",
    "text": "暂时我想等到期末考试看看嗯，结果，嗯，ok 就是短暂的结果吧。",
    "clipUrl": "/clips/jiatingbao/user8/0002.mp3",
    "startTime": 2737.6,
    "duration": 7.1
  },
  {
    "seq": 8,
    "dimension": "关键原声",
    "caption": "如果有效果，我会排除万难让他们学下去。",
    "text": "我觉得如果有效果，我会排除万难，让他们学下去。",
    "clipUrl": "/clips/jiatingbao/user8/0003.mp3",
    "startTime": 2772.4,
    "duration": 4.7
  },
  {
    "seq": 8,
    "dimension": "关键原声",
    "caption": "几个孩子同时在房间学完，就能一起出发……我孩子多就会想到这些。",
    "text": "你你三个孩子同时在自己的房间学完了，我们就可以一起出发。如果说你内蒙没学到，",
    "clipUrl": "/clips/jiatingbao/user8/0004.mp3",
    "startTime": 3497.6,
    "duration": 5.3
  },
  {
    "seq": 6,
    "dimension": "使用",
    "caption": "大宝主要用 + 小宝顺带用。",
    "text": "主要给大宝用的。",
    "clipUrl": "/clips/jiatingbao/user6/0001.mp3",
    "startTime": 414.2,
    "duration": 1.4
  },
  {
    "seq": 6,
    "dimension": "关键原声",
    "caption": "花这么多钱不一定能见到提分效果。",
    "text": "不一定能见到效果。",
    "clipUrl": "/clips/jiatingbao/user6/0002.mp3",
    "startTime": 785.7,
    "duration": 2.1
  }
];
