import { Project, ProjectFile, VOCItem } from '../types/voc';

export const PAISOU_SOURCE_LINKS = {
  briefing: 'https://guanghe.feishu.cn/wiki/PWA5wZGawiTvS2kK6aGcrBP5nWc',
  competitiveWalkthrough: 'https://guanghe.feishu.cn/wiki/FTjywFGSKihXOMkRprEckkR9ncd',
  competitiveSummary: 'https://guanghe.feishu.cn/wiki/Hex5wwKLXiM6RHkSgn7clVyQneV',
  quantitative: 'https://guanghe.feishu.cn/docx/HXiQdmdf0ovWcdx9v0oc5f8tn0c',
  jtbd: 'https://guanghe.feishu.cn/wiki/LjhIwF4wHiIBZgk56h0cnyTRnXe',
};

const PAISOU_FILE_DEFS = [
  { id: 'paisou_file_briefing', name: '洞察简报·拍搜调研近期发现' },
  { id: 'paisou_file_competitive_walkthrough', name: '拍搜AI竞品分析文档' },
  { id: 'paisou_file_competitive_summary', name: '竞品vs洋葱产品与营销总结' },
  { id: 'paisou_file_quantitative', name: '拍搜问卷定量报告' },
  { id: 'paisou_file_jtbd', name: '学生拍搜调研·JTBD访谈纪要' },
];

export const PAISOU_VOCS: VOCItem[] = [
  {
    id: 'paisou_001',
    brand: '洋葱拍搜',
    text: '用户主动谈“好用”时，第一反应不是“准”，而是“看得懂”。开放题中更常提到文字解析详细、真人讲解清晰，而不是单说出答案快。',
    respondent: '洞察简报',
    sentiment: 'positive',
    dimension: '产品体验',
    subDimension: '看得懂',
    sourceFileId: 'paisou_file_briefing',
    sourceFileName: '洞察简报·拍搜调研近期发现',
  },
  {
    id: 'paisou_002',
    brand: '洋葱拍搜',
    text: '准确是门槛，但不足以驱动推荐；正向推荐更集中在解析详细和讲解清晰，负向反馈则集中在答案不对。',
    respondent: '洞察简报',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: '准确率门槛',
    sourceFileId: 'paisou_file_briefing',
    sourceFileName: '洞察简报·拍搜调研近期发现',
  },
  {
    id: 'paisou_003',
    brand: '洋葱拍搜',
    text: '差异化机会可能在“校内提分型拍搜”：把讲得懂升级为步骤对、得分点对、能迁移。',
    respondent: '洞察简报',
    sentiment: 'positive',
    dimension: '产品体验',
    subDimension: '校内提分定位',
    sourceFileId: 'paisou_file_briefing',
    sourceFileName: '洞察简报·拍搜调研近期发现',
  },
  {
    id: 'paisou_004',
    brand: '洋葱拍搜',
    text: '时间紧迫度是第一变量：紧张时多数学生先看答案，解析只是顺带扫一眼；不紧张时愿意看步骤和视频，追求内化与迁移。',
    respondent: '洞察简报',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: '时间紧迫度',
    sourceFileId: 'paisou_file_briefing',
    sourceFileName: '洞察简报·拍搜调研近期发现',
  },
  {
    id: 'paisou_005',
    brand: '洋葱拍搜',
    text: '用户按题目难度和卡点类型分流拍搜产品：中等题作业纠错流向豆包，难题学透更适配洋葱以题找课和母题视频。',
    respondent: '洞察简报',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: '场景分流',
    sourceFileId: 'paisou_file_briefing',
    sourceFileName: '洞察简报·拍搜调研近期发现',
  },
  {
    id: 'paisou_006',
    brand: '洋葱拍搜',
    text: 'P0 应先补作业模式：诊断纠错和自由追问，占据中等题、计算题的高频场景；P1 再放大学习模式和同类变式练习。',
    respondent: '洞察简报',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: '产品优先级',
    sourceFileId: 'paisou_file_briefing',
    sourceFileName: '洞察简报·拍搜调研近期发现',
  },
  {
    id: 'paisou_007',
    brand: '行业竞品',
    text: '行业基础体验已成标配，头部竞品基本能够实现 90% 以上解答正确率与 15 秒内出答案，竞争开始从给答案转向教方法。',
    respondent: '竞品走查',
    sentiment: 'neutral',
    dimension: '竞品对比',
    subDimension: '行业基准',
    sourceFileId: 'paisou_file_competitive_walkthrough',
    sourceFileName: '拍搜AI竞品分析文档',
  },
  {
    id: 'paisou_008',
    brand: '洋葱拍搜',
    text: '洋葱拍搜在准度和速度上低于行业平均，复杂题生成经常失败，用时甚至达到 1 分钟以上。',
    respondent: '竞品走查',
    sentiment: 'negative',
    dimension: '竞品对比',
    subDimension: '准与快短板',
    sourceFileId: 'paisou_file_competitive_walkthrough',
    sourceFileName: '拍搜AI竞品分析文档',
  },
  {
    id: 'paisou_009',
    brand: '洋葱拍搜',
    text: '洋葱的分步讲解和 IP 互动让解题不再枯燥，极具品牌辨识度，但地基体验不牢会限制留存。',
    respondent: '竞品走查',
    sentiment: 'neutral',
    dimension: '竞品对比',
    subDimension: '洋葱味优势',
    sourceFileId: 'paisou_file_competitive_walkthrough',
    sourceFileName: '拍搜AI竞品分析文档',
  },
  {
    id: 'paisou_010',
    brand: '竞品',
    text: '准不只是答案正确，还包括题目识别、步骤完整、过程简洁、方法适龄、解析精准和针对原题讲题。',
    respondent: '竞品走查',
    sentiment: 'neutral',
    dimension: '竞品对比',
    subDimension: '准确性定义',
    sourceFileId: 'paisou_file_competitive_walkthrough',
    sourceFileName: '拍搜AI竞品分析文档',
  },
  {
    id: 'paisou_011',
    brand: '豆包',
    text: '豆包通过推荐问题、解题技巧、类似例题和几道类似题形成闭环，让学生能跟着走完一类题学习。',
    respondent: '竞品总结',
    sentiment: 'positive',
    dimension: '竞品对比',
    subDimension: '学习闭环',
    sourceFileId: 'paisou_file_competitive_summary',
    sourceFileName: '竞品vs洋葱产品与营销总结',
  },
  {
    id: 'paisou_012',
    brand: '洋葱拍搜',
    text: '洋葱在中层“学懂一道题”上的情感联结和易读性表现优秀，能体现用户愿意选择洋葱的理由：愿意用、能看懂。',
    respondent: '竞品总结',
    sentiment: 'positive',
    dimension: '产品体验',
    subDimension: '情感联结',
    sourceFileId: 'paisou_file_competitive_summary',
    sourceFileName: '竞品vs洋葱产品与营销总结',
  },
  {
    id: 'paisou_013',
    brand: '洋葱拍搜',
    text: '底层 AI 准确度与速度仍是首要标杆；要实现 DAU 翻倍，必须接住对答案、抄答案、看步骤的流量。',
    respondent: '竞品总结',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: 'DAU提频',
    sourceFileId: 'paisou_file_competitive_summary',
    sourceFileName: '竞品vs洋葱产品与营销总结',
  },
  {
    id: 'paisou_014',
    brand: '洋葱拍搜',
    text: '营销人设应强化“有趣+专业+亲近感”：不是温柔到没有原则，也不是专业到高高在上，而是平易近人、有耐心、讲解生动。',
    respondent: '竞品总结',
    sentiment: 'positive',
    dimension: '购买决策',
    subDimension: '营销人设',
    sourceFileId: 'paisou_file_competitive_summary',
    sourceFileName: '竞品vs洋葱产品与营销总结',
  },
  {
    id: 'paisou_015',
    brand: '洋葱拍搜',
    text: '学生侧营销应作为主要驱动，核心卖点是有趣、专业、亲近感；家长侧辅助表达孩子愿意自发学懂、家长省心。',
    respondent: '竞品总结',
    sentiment: 'neutral',
    dimension: '购买决策',
    subDimension: '传播策略',
    sourceFileId: 'paisou_file_competitive_summary',
    sourceFileName: '竞品vs洋葱产品与营销总结',
  },
  {
    id: 'paisou_016',
    brand: '洋葱拍搜',
    text: '定量报告显示：用户不是两类人，而是同一批人的两种状态。时间紧时是答案机器，时间松时想真正学懂。',
    respondent: '问卷定量',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: '状态切换',
    sourceFileId: 'paisou_file_quantitative',
    sourceFileName: '拍搜问卷定量报告',
  },
  {
    id: 'paisou_017',
    brand: '洋葱拍搜',
    text: '初中和高中，时间紧迫度的差异幅度大于成绩维度；时间紧迫度是行为差异的第一变量。',
    respondent: '问卷定量',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: '时间紧迫度',
    sourceFileId: 'paisou_file_quantitative',
    sourceFileName: '拍搜问卷定量报告',
  },
  {
    id: 'paisou_018',
    brand: '洋葱拍搜',
    text: '获得感呈现三层结构：找到卡点、掌握大招、举一反三。前两项是认知修复，第三项是能力验证。',
    respondent: '问卷定量',
    sentiment: 'positive',
    dimension: '产品体验',
    subDimension: '获得感',
    sourceFileId: 'paisou_file_quantitative',
    sourceFileName: '拍搜问卷定量报告',
  },
  {
    id: 'paisou_019',
    brand: '洋葱拍搜',
    text: '洋葱的增量在时间紧场景：宽松型用户中洋葱反超作业帮，但高压型用户中份额差距明显，速度是公认短板。',
    respondent: '问卷定量',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: '增量机会',
    sourceFileId: 'paisou_file_quantitative',
    sourceFileName: '拍搜问卷定量报告',
  },
  {
    id: 'paisou_020',
    brand: '洋葱拍搜',
    text: '举一反三是时间充裕时才会触发的深度需求，高紧迫用户选择率低于低紧迫用户，不应在高紧迫场景中强推。',
    respondent: '问卷定量',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: '举一反三',
    sourceFileId: 'paisou_file_quantitative',
    sourceFileName: '拍搜问卷定量报告',
  },
  {
    id: 'paisou_021',
    brand: '小猿学习机',
    text: '“针对错题，先尝试自己写，不会写（有一点思路就过程卡住）就拍搜。”用户会先看答案，再看过程，再对照自己的过程。',
    respondent: '用户1·初二·物理',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: '卡点定位',
    sourceFileId: 'paisou_file_jtbd',
    sourceFileName: '学生拍搜调研·JTBD访谈纪要',
  },
  {
    id: 'paisou_022',
    brand: 'DeepSeek',
    text: '“它可能会从直接从第一个跳到第四个步骤。”跳步太大、识别不准和方法超纲，会让学生理解断层。',
    respondent: '用户1·初二·物理',
    sentiment: 'negative',
    dimension: '产品体验',
    subDimension: '跳步断层',
    sourceFileId: 'paisou_file_jtbd',
    sourceFileName: '学生拍搜调研·JTBD访谈纪要',
  },
  {
    id: 'paisou_023',
    brand: '豆包',
    text: '作业量大、时间紧迫时，用户想要快速获得答案进行核对；时间充裕面对错题时，才想要详细、能用通俗例子讲解的解析。',
    respondent: '用户2·初二·化学',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: '时间分流',
    sourceFileId: 'paisou_file_jtbd',
    sourceFileName: '学生拍搜调研·JTBD访谈纪要',
  },
  {
    id: 'paisou_024',
    brand: '洋葱拍搜',
    text: '“洋葱会用能理解的角度来讲、举例子。”用户会点“听不懂”触发第二次解析，希望翻译成能听懂的通俗语言。',
    respondent: '用户2·初二·化学',
    sentiment: 'positive',
    dimension: '产品体验',
    subDimension: '通俗讲解',
    sourceFileId: 'paisou_file_jtbd',
    sourceFileName: '学生拍搜调研·JTBD访谈纪要',
  },
  {
    id: 'paisou_025',
    brand: '豆包',
    text: '“我母亲还有我父亲都不会……DeepSeek 的方法太过高端，实在是看不懂。”超纲方法需要家长翻译，增加学习成本。',
    respondent: '用户7·六年级·数学',
    sentiment: 'negative',
    dimension: '产品体验',
    subDimension: '方法适龄',
    sourceFileId: 'paisou_file_jtbd',
    sourceFileName: '学生拍搜调研·JTBD访谈纪要',
  },
  {
    id: 'paisou_026',
    brand: '洋葱拍搜',
    text: '“看洋葱十道题错5道，不看洋葱十道题错8道。”对难题，用户会跳过文字解析直奔视频，反复看两遍以上，再记到笔记本。',
    respondent: '用户8·初一·数学',
    sentiment: 'positive',
    dimension: '产品体验',
    subDimension: '难题学透',
    sourceFileId: 'paisou_file_jtbd',
    sourceFileName: '学生拍搜调研·JTBD访谈纪要',
  },
  {
    id: 'paisou_027',
    brand: '豆包',
    text: '“告诉我哪一步错了。”中等难度题已有结果但存疑时，用户需要对话框直接描述困惑，快速定位具体错误点。',
    respondent: '用户8·初一·数学',
    sentiment: 'positive',
    dimension: '产品体验',
    subDimension: '针对性纠错',
    sourceFileId: 'paisou_file_jtbd',
    sourceFileName: '学生拍搜调研·JTBD访谈纪要',
  },
  {
    id: 'paisou_028',
    brand: '快对',
    text: '“快对，你只要一拍它就会马上可以找出答案。”老师要求自批自改时，用户只要最快看到答案，不需要讲解和思路。',
    respondent: '用户8·初一·数学',
    sentiment: 'neutral',
    dimension: '产品体验',
    subDimension: '高效核对',
    sourceFileId: 'paisou_file_jtbd',
    sourceFileName: '学生拍搜调研·JTBD访谈纪要',
  },
];

export type PaisouOnionRelation = '忠实粉' | '摇摆用户' | '偶尔使用' | '被竞品截流';
export type PaisouOnionStatus = '洋葱价值样本' | '场景型使用' | '机会/边界样本';

export interface PaisouUserStory {
  id: string;
  name: string;
  meta: string;
  job: string;
  need: string;
  friction: string;
  quote: string;
  onionMoment?: string;
  grade: string;
  region: string;
  subjects: string[];
  learningStatus: string;
  pressure: string;
  currentGoal: string;
  answerVsLearn: string;
  relation: PaisouOnionRelation;
  onionStatus: PaisouOnionStatus;
  onionStatusNote: string;
  tools: string[];
  primaryCompetitor: string;
  oneLine: string;
  scene: string;
  jtbd: string;
  whyOnionWins: string[];
  whySwitches: string[];
  retention: string;
  risk: string;
  marketing: {
    angle: string;
    hook: string;
    channels: string[];
    avoid: string;
  };
}

export const PAISOU_SURVEY_SIGNALS = {
  sample: [
    { label: '问卷样本量', value: '7,261', note: '问卷星原始数据' },
    { label: '学生占比', value: '95.4%', note: '样本主体是学生本人' },
    { label: '知道拍题精学', value: '86.1%', note: '已具备功能认知基础' },
    { label: '近一个月使用更多', value: '56.5%', note: '明显更多 + 稍多一些' },
  ],
  toolShare: [
    { name: '洋葱 AI 拍题精学', value: 39.9, description: '当前第一常用拍搜工具' },
    { name: '作业帮', value: 15.3, description: '速度和题库形成分流' },
    { name: '豆包/豆包爱学', value: 13.4, description: '追问和对话感形成分流' },
  ],
  stageShare: [
    { stage: '小学', onion: 38.4, homework: 14.9, doubao: 14.7 },
    { stage: '初中', onion: 42.2, homework: 15.0, doubao: 11.9 },
    { stage: '高中', onion: 33.4, homework: 20.4, doubao: 16.8 },
  ],
};

export const PAISOU_INTERVIEW_EVIDENCE = [
  {
    theme: '速度慢',
    quote: '超过6秒就会烦躁。',
    note: '高压作业场景里，等待感会直接触发切换工具。',
  },
  {
    theme: '答案不准',
    quote: '讲题过程还是对的，但是答案依旧是错的。',
    note: '准确性是信任门槛，不能只靠讲解体验补偿。',
  },
  {
    theme: '识别/年级匹配',
    quote: '我拍的是初中题，它给我高中的回复。',
    note: '方法适龄和学段匹配会影响学生是否继续看。',
  },
  {
    theme: '竞品切换',
    quote: '给了跟没给差不多，只能用其他 AI 软件。',
    note: '当结果无法马上服务当前任务时，学生会快速转向竞品。',
  },
  {
    theme: '洋葱讲得懂',
    quote: '洋葱会用能理解的角度来讲、举例子。',
    note: '洋葱的优势不是单纯快，而是把题讲到学生愿意继续听。',
  },
];

export const PAISOU_USERS: PaisouUserStory[] = [
  {
    id: 'wu-yuyao',
    name: '吴语遥',
    meta: '江苏苏州 · 初二 · 小猿学习机 & DeepSeek · 物理',
    job: '考前复习中等难度错题，希望找到过程卡点并用同类题验证是否真的懂。',
    need: '步骤完整、方法适龄、能做同类题',
    friction: 'DeepSeek 跳步大、拍照麻烦，部分解析使用没学过的知识。',
    quote: '它可能会从直接从第一个跳到第四个步骤。',
    grade: '初二',
    region: '江苏苏州',
    subjects: ['数学', '物理'],
    learningStatus: '中上水平，遇到综合题会卡在步骤衔接',
    pressure: '混合型：作业时间紧时先求快，复盘时愿意学懂',
    currentGoal: '把不会的步骤拆开，确认自己到底卡在哪里',
    answerVsLearn: '先要能跟上步骤，再希望举一反三',
    relation: '被竞品截流',
    onionStatus: '机会/边界样本',
    onionStatusNote: '她的拍搜主链路在小猿学习机和 DeepSeek，洋葱目前更多是试卷/知识点补充入口。',
    tools: ['洋葱课程/试卷', '小猿学习机', 'DeepSeek'],
    primaryCompetitor: '小猿学习机 / DeepSeek',
    oneLine: '她不是洋葱拍搜用户样本：拍搜首选小猿和 DeepSeek，洋葱价值在找题、补课和知识点复习。',
    scene: '期末复习时会在洋葱找试卷让父母打印；不会的题主要用学习机“作业批改”和 DeepSeek 拍搜，再用精准学做同类题。',
    jtbd: '当我卡在一道题中间步骤时，帮我把复杂推理拆成可以跟上的连续动作，让我知道不是只抄到了答案，而是真的能复现。',
    whyOnionWins: ['洋葱的试卷和知识点课已经进入她的复习链路', '学校没听懂的数学/物理知识点会回到洋葱补课', '如果拍搜能给适龄不跳步解析，有机会从补课延伸到拍搜'],
    whySwitches: ['小猿学习机是当前复习和拍搜主入口', 'DeepSeek能追问，但跳步和识别会带来理解断层', '她当前拍搜不会第一时间想到洋葱'],
    retention: '当前不能写成洋葱拍搜留存样本；真实机会是把“能补知识点”的信任迁移到拍搜解题。',
    risk: '如果把她包装成洋葱拍搜用户会失真；洋葱要先证明拍搜也能适龄、准确、不跳步。',
    marketing: {
      angle: '把“跳步解析”变成“每一步都有人带你走”。',
      hook: '卡住的不是答案，是中间那一步。',
      channels: ['B站学习区', '小红书学生笔记', '短视频题目拆解'],
      avoid: '不要只说“秒出答案”，这会把她推向更快的竞品。',
    },
  },
  {
    id: 'xu-tongxue',
    name: '徐同学',
    meta: '上海 · 初二 · 豆包 & 洋葱 · 化学/语文',
    job: '时间紧时用豆包快速核对，时间充裕时用洋葱把错题讲懂。',
    need: '快速答案与通俗讲解之间切换',
    friction: '洋葱步骤更完整，但着急时确认环节和等待感会影响选择。',
    quote: '洋葱会用能理解的角度来讲、举例子。',
    grade: '初二',
    region: '上海',
    subjects: ['化学', '语文', '数学'],
    learningStatus: '时间管理压力明显，工具选择高度受作业截止影响',
    pressure: '高压型：赶作业时先要结果，空下来才会深学',
    currentGoal: '在不同时间状态下快速切换：赶时间拿答案，不赶时间学懂',
    answerVsLearn: '时间紧时对答案，时间松时想学懂',
    relation: '摇摆用户',
    onionStatus: '场景型使用',
    onionStatusNote: '豆包更常用、更快；洋葱在时间充裕、想把错题讲懂时被选择。',
    tools: ['洋葱', '豆包'],
    primaryCompetitor: '豆包',
    oneLine: '同一个人会在“答案机器”和“想真正学懂”之间切换，关键变量不是学段，而是时间。',
    scene: '晚间作业堆在一起时，会优先用豆包快速问；周末或复盘时，才愿意打开洋葱看详细讲解。',
    jtbd: '当我时间很紧时，先帮我快速确认方向；当我时间充裕时，再带我把题真正讲懂。',
    whyOnionWins: ['讲解详细，适合复盘', '有知识点视频能补基础', '更像学习而不是单纯问答'],
    whySwitches: ['豆包能连续追问', '豆包进入成本低，回答更快', '洋葱如果强推长讲解会和赶作业状态冲突'],
    retention: '能让她自己选择“极速看答案 / 深度学懂”模式，就能承接两种状态。',
    risk: '如果不识别时间压力，她会在最常见的作业高压场景被豆包截走。',
    marketing: {
      angle: '同一道题，赶时间先过关，有时间再学懂。',
      hook: '别逼自己现在学透，先找到卡点也算赢。',
      channels: ['抖音学生侧短视频', '小红书作业场景', '校园社群转发'],
      avoid: '不要把“举一反三”作为所有场景的第一卖点。',
    },
  },
  {
    id: 'xiaojie',
    name: '小杰',
    meta: '广东揭阳 · 初一 · 元宝/讯飞/作业帮/小猿 · 数学',
    job: '遇到大题找不到突破口时，需要视频和变式题把思路转成可复用方法。',
    need: '生动视频、即时变式、规范步骤',
    friction: '只给答案不够，需要知道突破口和得分点。',
    quote: '遇到难题，找不到解题突破口。',
    grade: '初一',
    region: '广东揭阳',
    subjects: ['数学'],
    learningStatus: '数学较强，主要在压轴题和分类讨论上验证思路',
    pressure: '宽松型：愿意在难题上花时间',
    currentGoal: '确认高难题解法是否完整，并通过变式证明自己会了',
    answerVsLearn: '更偏学透一类题',
    relation: '被竞品截流',
    onionStatus: '机会/边界样本',
    onionStatusNote: '文档里他的现用工具是元宝、科大讯飞、作业帮、小猿，洋葱不是当前拍搜工具。',
    tools: ['腾讯元宝', '科大讯飞学习机', '小猿', '作业帮'],
    primaryCompetitor: '学习机 / 小猿',
    oneLine: '他验证的是强学生会为“视频讲解 + 举一反三 + 完整解析”买单，但当前不是洋葱使用样本。',
    scene: '普通题很少依赖拍搜，主要在压轴题卡住、想验证多解法或找同类题时使用。',
    jtbd: '当我已经能看懂基础解析时，帮我找到更优解法和同类变式，让我确认这类题我真的掌握了。',
    whyOnionWins: ['如果洋葱能把知识点和题型连接起来，有机会承接这类高阶需求', '视频讲解和变式训练是他认可的成功标准', '“学透一类题”的闭环对强学生有吸引力'],
    whySwitches: ['学习机入口更顺手', '小猿题库覆盖更像刷题场景', '如果没有变式和总结，单题解析价值有限'],
    retention: '这不是洋葱已被选择的证据，而是说明洋葱可以争取“高阶学习闭环”这个位置。',
    risk: '如果洋葱只展示基础讲解，会被他判定为不够进阶，也很难从学习机和小猿手里抢入口。',
    marketing: {
      angle: '不是看懂这道题，是拿下这一类题。',
      hook: '压轴题真正的爽感，是下一道类似题你自己做出来。',
      channels: ['B站压轴题拆解', '初中数学社群', '小红书学霸笔记'],
      avoid: '不要用“保姆级”作为唯一表达，强学生会觉得低估自己。',
    },
  },
  {
    id: 'ding-tongxue',
    name: '丁同学',
    meta: '安徽六安 · 初三 · 步步高/作业帮/洋葱 · 数理化英',
    job: '多学科复习时，希望拍搜能快速确认答案并补上老师没讲透的点。',
    need: '全科覆盖、步骤规范、复习效率',
    friction: '不同学科答案稳定性和课程匹配度不一致。',
    quote: '作业和复习都需要能快速判断哪里错了。',
    grade: '初三',
    region: '安徽六安',
    subjects: ['数学', '物理'],
    learningStatus: '中考压力下多工具并用，按题目难度分配工具',
    pressure: '高压型：中等题求快，难题才深看',
    currentGoal: '中等题快速过，压轴题找新解法和相关知识点',
    answerVsLearn: '按题目难度切换',
    relation: '摇摆用户',
    onionStatus: '场景型使用',
    onionStatusNote: '作业帮频率最高；洋葱用于压轴大题、相关深度课和不一样的解法。',
    tools: ['作业帮', '洋葱'],
    primaryCompetitor: '作业帮',
    oneLine: '他不是不用洋葱，而是只在洋葱最有价值的“难题复盘”场景才打开。',
    scene: '赶作业和刷题时先用作业帮；遇到压轴题、新题型或看不懂标准解析时，才切到洋葱。',
    jtbd: '当题目只是需要完成时，帮我快；当题目影响我提分时，帮我真正找到突破口。',
    whyOnionWins: ['难题讲解更有耐心', '能关联知识点和视频课', '更适合复盘和补漏洞'],
    whySwitches: ['作业帮题库和速度更强', '中考压力下不愿等待', '普通题没有深学动力'],
    retention: '洋葱要成为“值得为难题多花一分钟”的工具，而不是所有题都要求深学。',
    risk: '如果在中等题上也强行重流程，会加剧流失。',
    marketing: {
      angle: '普通题求快，关键题要真懂。',
      hook: '中考提分，不靠抄过一题，靠抓住真正卡分的那一步。',
      channels: ['初三备考内容', '短视频难题卡点拆解', '家长侧提分故事'],
      avoid: '不要否定快速对答案需求，它是他的真实状态。',
    },
  },
  {
    id: 'lv-tongxue',
    name: '吕同学',
    meta: '黑龙江绥芬河 · 初二 · 作业帮 · 数学/英语',
    job: '作业中遇到不会的题，希望先把答案和步骤跑通，再判断是否需要深学。',
    need: '答案快、步骤清楚、低操作成本',
    friction: '讲解不够细时，看完还是不知道下一步怎么做。',
    quote: '就去洋葱看一眼这个知识点，然后再回来再推一遍。',
    grade: '初二',
    region: '黑龙江绥芬河',
    subjects: ['数学'],
    learningStatus: '会担心直接抄答案痕迹，需要把答案转化成自己的步骤',
    pressure: '混合型：要完成作业，也要看起来是自己理解过',
    currentGoal: '看懂卡住的那一步，再写成自己的解题过程',
    answerVsLearn: '先理解关键步骤，再输出自己的答案',
    relation: '忠实粉',
    onionStatus: '洋葱价值样本',
    onionStatusNote: '他每天使用洋葱预习/复习，考前会用洋葱突击和刷题；作业帮只是偶尔拍题补充。',
    tools: ['洋葱', '作业帮'],
    primaryCompetitor: '作业帮',
    oneLine: '他不是单纯作业帮用户：洋葱已经进入日常预习、复习和考前突击，是稳定学习入口。',
    scene: '每天会拍题，也会用洋葱预习/复习；考前会用洋葱的考前突击和刷题，作业帮更多是偶尔补充。',
    jtbd: '当我必须完成作业但又不想机械抄答案时，帮我理解关键步骤，并能用自己的话写出来。',
    whyOnionWins: ['讲解语气更像带着理解', '视频/动画能帮他转化表达', '不只是给答案，而是解释过程'],
    whySwitches: ['作业帮标准答案更快', '需要马上交作业时没有耐心', '洋葱慢会让他放弃理解'],
    retention: '洋葱已经承担“学会知识点 + 考前复习”的稳定入口，价值不是秒出答案，而是让他能继续学下去。',
    risk: '如果拍搜场景只强调完整学透，仍可能在即时核答案时被作业帮分流。',
    marketing: {
      angle: '不是帮你抄，是帮你写出自己懂的步骤。',
      hook: '答案能抄，思路得变成自己的。',
      channels: ['学生侧短视频', '作业场景素材', '小红书学习方法'],
      avoid: '不要把用户描述成“偷懒抄答案”，这会削弱共情。',
    },
  },
  {
    id: 'nuoshi',
    name: '诺诗',
    meta: '湖南永州 · 初三 · 作业帮 · 数学/英语',
    job: '希望把当前题讲懂，并能迁移到同类题，形成自己的解题记录。',
    need: '知识点提示、笔记沉淀、情绪价值',
    friction: '真人视频或机械解析容易无聊，不能持续听进去。',
    quote: '洋葱更容易理解，更有兴趣一点。',
    onionMoment: '上次做几何题，先看了一点点解析，突然想到老师上课讲过的知识点，一下就知道怎么做了。',
    grade: '初三',
    region: '湖南永州',
    subjects: ['数学', '物理'],
    learningStatus: '普通班中差水平，能听懂就是最大的获得感',
    pressure: '高压型：中考前需要低门槛、低挫败感',
    currentGoal: '先听懂这道题，降低不会题带来的挫败',
    answerVsLearn: '想学懂，但需要更强情绪价值',
    relation: '忠实粉',
    onionStatus: '洋葱价值样本',
    onionStatusNote: '最常用拍题软件是洋葱，其次作业帮；洋葱赢在更容易理解、更有兴趣和情绪价值。',
    tools: ['洋葱', '作业帮'],
    primaryCompetitor: '作业帮',
    oneLine: '她喜欢洋葱不是因为最快，而是因为讲得温柔、有趣，像有人陪她把题弄懂。',
    scene: '题目看不懂、被标准解析劝退时，会选择洋葱，因为洋葱的语气和动画让她愿意继续听。',
    jtbd: '当我因为不会题而沮丧时，给我一个不压迫的讲解，让我先听懂并恢复一点信心。',
    whyOnionWins: ['有趣和亲近感降低抗拒', '视频/动画适合中差生理解', '鼓励式表达能延长学习耐心'],
    whySwitches: ['作业帮更快完成作业', '如果洋葱识别慢或不准会破坏信任', '讲解太长时也会疲惫'],
    retention: '这是洋葱最典型的忠实粉：真正买单的是“能看懂 + 愿意继续学”。',
    risk: '如果为了快而牺牲陪伴感，会损失洋葱最独特的品牌资产。',
    marketing: {
      angle: '不会题也不用怕，有人慢慢陪你讲懂。',
      hook: '第一次觉得数学题没有那么凶。',
      channels: ['抖音情绪价值短视频', '小红书学生反馈', 'B站动画讲题切片'],
      avoid: '不要做成纯学霸语气或高压提分语气。',
    },
  },
  {
    id: 'mengmei',
    name: '梦梅',
    meta: '甘肃兰州 · 六年级 · 学而思平板/豆包/小猿 · 数学/语文',
    job: '父母也不会做拔高题时，希望工具给出思路，再由家长翻译成已学知识。',
    need: '方法适龄、标准步骤、家长可解释',
    friction: '根号、方程等超纲解法让孩子直接看不懂。',
    quote: 'DeepSeek 的方法太过高端，实在是看不懂。',
    grade: '六年级',
    region: '甘肃兰州',
    subjects: ['数学'],
    learningStatus: '低龄小升初阶段，需要家长协助判断工具和内容难度',
    pressure: '宽松型：家长更关注适龄和不超纲',
    currentGoal: '遇到不会题时先看懂基础解释，不被超纲内容吓退',
    answerVsLearn: '想学懂，但需要适龄表达',
    relation: '被竞品截流',
    onionStatus: '机会/边界样本',
    onionStatusNote: '当前使用学而思平板、小猿/作业帮和豆包；她说明低龄用户更依赖设备入口、适龄讲解和家长翻译。',
    tools: ['学而思平板', '豆包', '小猿', '作业帮'],
    primaryCompetitor: '学习机 / 豆包',
    oneLine: '她不是不想用洋葱，而是低龄用户需要更适龄、更少超纲、更能让家长放心的解释。',
    scene: '小升初前遇到不会的数学题，家长会参与选择工具；如果解释超纲或像大人话术，会被学习机或家长讲解替代。',
    jtbd: '当我还没进入初中体系时，用我能听懂的方式解释题目，并让家长确认这不是超纲乱讲。',
    whyOnionWins: ['动画和角色天然适合低龄理解，这是洋葱可能切入的价值', '知识点视频比纯文字更友好', '如果能让家长感到适龄和可信，洋葱有机会进入家庭辅助链路'],
    whySwitches: ['学习机入口更受家长控制', '豆包需要家长辅助追问', '超纲表达会让家长不放心'],
    retention: '这不是洋葱使用样本，而是在提醒洋葱：低龄用户要先过“适龄、可信、家长能理解”这一关。',
    risk: '如果只追求大模型式完整解析，可能把六年级用户和家长一起推走。',
    marketing: {
      angle: '孩子听得懂，家长也放心的拍题讲解。',
      hook: '不是把答案讲复杂，而是把难题讲到孩子能懂。',
      channels: ['小红书家长侧', '微信社群', '小升初内容'],
      avoid: '不要强调过度进阶和超纲拔高。',
    },
  },
  {
    id: 'xiaolin',
    name: '小林',
    meta: '广西南宁 · 初一 · 豆包/洋葱/快对 · 数学',
    job: '难题用洋葱视频吃透，中等题用豆包定位哪步错，简单题用快对秒看答案。',
    need: '按题型切换：学透、纠错、核对',
    friction: '洋葱旧版缺少对话框，不能直接问“哪一步错了”。',
    quote: '洋葱的不可替代性是可以上课。',
    onionMoment: '坚持用洋葱后，数学从 60 多分提到 80 多分；“看洋葱十道题错5道，不看十道题错8道。”',
    grade: '初一',
    region: '广西南宁',
    subjects: ['数学'],
    learningStatus: '自驱中等生，能区分简单题、中等题、难题的工具价值',
    pressure: '混合型：按题目价值决定投入时间',
    currentGoal: '简单题快对，中等题问错因，难题看视频学透',
    answerVsLearn: '分层处理：快对答案、定位卡点、深度学懂',
    relation: '忠实粉',
    onionStatus: '洋葱价值样本',
    onionStatusNote: '洋葱 10/10，一周约 6 次拍数学大题；豆包和快对分别满足纠错、核答案。',
    tools: ['洋葱', '豆包', '快对'],
    primaryCompetitor: '豆包 / 快对',
    oneLine: '他最接近理想拍搜用户：知道什么时候要快，什么时候要找卡点，什么时候要学透。',
    scene: '自习和作业过程中按题目难度切换工具：快对用于简单核答案，豆包用于追问，洋葱用于难题和知识点复盘。',
    jtbd: '当我面对不同难度题目时，帮我选择合适深度：能快就快，需要懂就讲透。',
    whyOnionWins: ['难题视频讲解有价值', '知识点补充让他形成体系', '洋葱适合主动学习者做复盘'],
    whySwitches: ['快对在简单题上效率更高', '豆包追问更自由', '如果洋葱无法快速切模式，会被拆分使用'],
    retention: '他证明洋葱不必赢下所有场景，只要成为“关键题学懂”的首选。',
    risk: '一刀切的深度讲解会降低他对洋葱的效率评价。',
    marketing: {
      angle: '聪明学生不是每题都深学，而是知道哪题值得学透。',
      hook: '简单题快过，关键题真懂。',
      channels: ['B站学习策略', '小红书自驱学习', '抖音场景对比'],
      avoid: '不要把快对答案和深度学习对立起来。',
    },
  },
];

export const PAISOU_REPORT = {
  verdict: '拍搜不是单纯“答案工具”竞争，而是在“快速解决问题”和“真正讲懂、能迁移、能提分”之间寻找产品定位。',
  metrics: [
    ['9,139', '问卷样本', '覆盖小学、初中、高中拍题答疑用户'],
    ['8', 'JTBD访谈', '围绕真实作业、复习和错题场景拆解'],
    ['13+', '竞品走查', '覆盖通用AI、教育App与学习机'],
    ['5', '来源文档', '简报、竞品、定量、访谈、营销总结'],
  ],
  pillars: [
    {
      title: '准和快是地基，不是差异化终点',
      impact: '决定用户是否愿意在高频作业场景里打开洋葱。',
      findings: ['行业头部已能做到高正确率和 15 秒内出答案', '洋葱复杂题速度和失败率仍是短板', '准还包括识别、步骤、适龄、得分点和原题匹配'],
      action: '先补“极速答案 + 关键步骤”，再承接深度讲解。',
    },
    {
      title: '看得懂才会产生口碑和复访',
      impact: '影响学生是否觉得自己真的学会，也影响家长侧的有效感。',
      findings: ['用户说好用时更常说解析详细、讲解清晰', '洋葱的情感联结和易读性是优势', '跳步、超纲、文绉绉会造成理解断层'],
      action: '保留洋葱味，但压缩冗余步骤，优先讲卡点。',
    },
    {
      title: '时间紧迫度决定用户要哪种模式',
      impact: '决定 DAU 增长能否接住底层高频需求。',
      findings: ['时间紧时用户先看答案', '时间松时用户愿意看步骤和视频', '同一批用户会在两种状态间切换'],
      action: '产品需要“快扫模式 / 深学模式”显性切换。',
    },
    {
      title: '校内提分型拍搜是洋葱的差异化机会',
      impact: '把拍搜从工具入口升级为学习闭环入口。',
      findings: ['得分点、规范步骤、同类迁移是校内场景强需求', '精准找卡点是跨学段共识', '以题找课和母题视频是洋葱护城河'],
      action: '用“找卡点 → 得分点 → 变式验证”做成核心路径。',
    },
  ],
};

export const PAISOU_COMPETITIVE = {
  landscape: [
    ['AI+教育App', '作业帮、快对AI、小猿AI', '题库积累强，准和快突出，正在用 AI 讲解补理解。'],
    ['AI大模型产品', '豆包、夸克、千问、元宝', '对话能力强，正在把 AI 变成一对一老师和学习生态。'],
    ['学习机产品', '小猿、讯飞、学而思、步步高', '全流程学习智能体，强调精准学、错题分析和个性化学习。'],
  ],
  dimensions: [
    ['准', '题目识别、答案准确、步骤完整、方法适龄、解析精准。'],
    ['快', '拍完即出结果，尤其服务对答案和作业批改。'],
    ['懂', '解释是否清楚、是否能追问、是否降低理解门槛。'],
    ['透', '同类题、错题本、知识图谱和个性化学习闭环。'],
  ],
  competitors: [
    ['豆包', '对话追问和闭环问题推荐强，适合定位某一步错误；但讲解有时太 AI，需要多轮追问。'],
    ['作业帮/快对', '答案和题库效率强，适合核对答案；但深度学懂和情绪价值不足。'],
    ['小猿/学习机', '作业批改、精准学和全流程学习生态强；但部分 AI 讲解仍有准确性和识别争议。'],
    ['夸克/通用AI', '速度快、知识点视频推荐丰富；答案更像陈列，步骤细致度和情感联结不足。'],
    ['洋葱', '分步讲解、IP互动、母题视频和课程生态有辨识度；短板是速度、复杂题成功率和自由追问。'],
  ],
};

export const PAISOU_QUANTITATIVE = {
  tables: [
    {
      title: '学段竞争格局',
      rows: [
        ['小学', '作业帮 20.5%', '洋葱 18.3%', '步步高学习机 13.1%'],
        ['初中', '作业帮 24.5%', '洋葱 20.7%', '豆包 12.5%'],
        ['高中', '作业帮 29.6%', '洋葱 24.1%', '豆包 11.2%'],
      ],
    },
    {
      title: '时间紧迫度分布',
      rows: [
        ['高压型', '小学 25.6%', '初中 26.2%', '高中 32.7%'],
        ['混合型', '小学 29.0%', '初中 37.0%', '高中 38.1%'],
        ['宽松型', '小学 27.4%', '初中 26.8%', '高中 22.6%'],
      ],
    },
    {
      title: '获得感 Top 体验',
      rows: [
        ['精准找卡点', '全量 51.4%', '初中 54.6%', '高中 57.0%'],
        ['得分点/解题大招', '全量 48.7%', '初中 50.5%', '高中 52.1%'],
        ['举一反三', '全量 47.6%', '小学 51.3%', '低紧迫 53.8%'],
      ],
    },
  ],
  implications: [
    '产品首先要判断用户当前是赶时间还是有时间，再决定给答案、给步骤还是给深度学习路径。',
    '高紧迫场景先解决速度，再做 30 秒内精准找卡点；低紧迫场景才适合推举一反三和课程闭环。',
    '较差学生的“对答案”更像习惯，不应只靠深度解析转化，需要完全不同的轻量引导。',
  ],
};

export const PAISOU_MARKETING = {
  personas: [
    ['严谨专业型', '强调准、得分点、规范步骤和老师判分逻辑，适合家长侧信任建立。'],
    ['温柔陪伴型', '强调耐心、鼓励和不责备，适合降低学生追问压力。'],
    ['生态整合型', '强调错题、课程、知识点和学习计划闭环，适合长期价值表达。'],
  ],
  strategy: [
    '洋葱人设应强化“有趣 + 专业 + 亲近感”，形成有洋葱味的拍搜表达。',
    '学生侧作为主要驱动：短视频展示讲解趣味性、愿意学、讲得懂。',
    '家长侧作为辅助驱动：表达孩子愿意自发学懂、家长省心、学习有效。',
    '营销不能脱离产品地基：速度慢和准确率低会让被营销吸引来的用户在关键时刻流向竞品。',
  ],
};

export function buildPaisouProject(): Project {
  const files: ProjectFile[] = PAISOU_FILE_DEFS.map((file) => ({
    ...file,
    category: 'document',
    status: 'ready',
    uploadedAt: 1767225600000,
    vocList: PAISOU_VOCS.filter((item) => item.sourceFileId === file.id),
  }));

  return {
    id: 'paisou_project',
    name: '拍搜产品全流程调研',
    createdAt: 1767225600000,
    quarter: '2026Q1',
    files,
    category: '产品功能',
    team: ['产品', '策略', '增长'],
    methods: ['桌面研究', '定量调研', '定性调研'],
    status: '已完成',
    summaryData: {
      coreFindings: [
        '拍搜不是单纯答案工具竞争，而是在快速解决问题和真正讲懂、能迁移、能提分之间寻找产品定位。',
        '准和快是进入高频作业场景的地基；看得懂、步骤对、得分点对才是洋葱差异化。',
        '时间紧迫度是第一变量，同一批学生会在答案机器和深度学习两种状态间切换。',
        '洋葱应先补作业纠错与自由追问，再放大以题找课、母题视频和同类变式的学习闭环。',
      ],
      actionItems: [
        '上线极速答案/关键步骤入口，优先解决高紧迫场景的打开率。',
        '建立快扫模式与深学模式，减少用户在不同目的间的路径摩擦。',
        '围绕找卡点、得分点、变式验证重构校内提分型拍搜路径。',
        '营销侧统一“有趣+专业+亲近感”的洋葱拍搜人设。',
      ],
      methodology: '综合 5 份飞书资料：拍搜调研洞察简报、竞品走查、竞品与营销总结、定量问卷报告、8 位学生 JTBD 访谈纪要。',
      generatedAt: 1767225600000,
    },
  };
}
