import type { PortraitData } from '../types/research';

export const PORTRAIT_FRAMEWORK = ['教育理念', '投入程度', '决策方式', '核心需求', '典型行为'];

export const DEFAULT_PORTRAITS: Record<string, PortraitData> = {
  default_project: {
    framework: PORTRAIT_FRAMEWORK,
    source: '小学用户画像调研报告-23年2月、初中用户画像调研报告-23年9月、高中用户画像调研报告-23年12月',
    updatedBy: '编辑者',
    personas: [
      {
        id: 'primary-fun-companion',
        name: '小学｜好玩乐学陪伴型',
        definition: '把洋葱当成有趣、可探索的学习空间，活跃来自动画课程、PK、日常练习和陪伴感。',
        distribution: '小学活跃用户代表',
        educationPhilosophy: '先让孩子愿意学、持续学，再谈提分和拔高。',
        investment: '中低到中高投入；家长更愿意为兴趣、习惯和可见进步付费',
        decisionStyle: '孩子喜欢和学习兴趣提升是关键，家长需要看到学习过程与效果反馈',
        coreNeeds: ['提高学习兴趣', '培养预习复习习惯', '有趣陪伴与及时正反馈'],
        typicalBehaviors: ['使用教材同步和日常练习', '参与 PK、次元书桌等激励功能', '周末或晚间自主探索课程'],
        quotes: ['因为它里面有很多好看的课程，用游戏化的课程来改编视频。里面可以 PK 巩固，还有日常练习。'],
      },
      {
        id: 'primary-habit-parent',
        name: '小学｜习惯培养家长',
        definition: '家长更看重辅助学习、错题总结、预习复习和良好习惯养成，不只关心课程数量。',
        distribution: '小学家长代表',
        educationPhilosophy: '小学阶段重在学习习惯、兴趣和基础能力，不急于只做应试补课。',
        investment: '愿意为有效果和能养成习惯的工具付费，但对高价会谨慎',
        decisionStyle: '先观察孩子是否主动用、是否有进步，再决定是否付费或续费',
        coreNeeds: ['学习习惯养成', '错题总结和举一反三', '家长可见的学情反馈'],
        typicalBehaviors: ['要求孩子先复习再预习', '关注错题本和学情报告', '把洋葱定位为辅助学习软件'],
        quotes: ['我认为它是一个辅助的有基础有拔高有扩展的学习软件。'],
      },
      {
        id: 'primary-price-sensitive',
        name: '小学｜价值未被看见型',
        definition: '学生可能想用或想付费，但家长不了解洋葱价值，或担心贵、没效果、孩子坚持不下来。',
        distribution: '小学流失/不付费用户代表',
        educationPhilosophy: '学习可以靠自己，付费必须证明值得。',
        investment: '低投入或延迟投入；对价格、效果和坚持风险敏感',
        decisionStyle: '需要先看到学习效果、使用方法和家长端反馈，否则倾向观望',
        coreNeeds: ['大白话价值说明', '付费前效果验证', '降低家长不确定感'],
        typicalBehaviors: ['使用免费内容即可满足预习复习', '不主动向家长开口付费', '担心买了不用或效果不好'],
        quotes: ['价格太贵了不知道效果怎么样。'],
      },
      {
        id: 'junior-self-disciplined-top',
        name: '初中｜自律学霸巩固型',
        definition: '成绩较好、有明确目标和规划，能把洋葱用于薄弱学科补强、优势学科刷题和预习复习闭环。',
        distribution: '初中典型付费/高活用户',
        educationPhilosophy: '多学科压力下，先把薄弱学科补齐，同时保持优势学科的练习强度。',
        investment: '中高投入；愿为省时间、内容好和长期使用价值付费',
        decisionStyle: '孩子主动认可内容，家长再比较性价比、管控和学习效果',
        coreNeeds: ['薄弱学科查漏补缺', '短时高效讲解', '刷题强化和错题复盘'],
        typicalBehaviors: ['当天知识点复习后再做作业', '用作业题型速攻和日常练习', '结合教辅书和洋葱预习复习'],
        quotes: ['其实家里也有学习平板，我说给他拿出来让他用。他说：课程内容比洋葱差。'],
      },
      {
        id: 'junior-confidence-builder',
        name: '初中｜错题解析提效型',
        definition: '面对数学或理科不稳定，希望通过经典题型、详细解析和错题本建立信心，减少家长辅导冲突。',
        distribution: '初中家长高价值感用户',
        educationPhilosophy: '初中学习不只是听懂，还要知道自己错在哪里、如何模仿正确思路。',
        investment: '中高投入；愿为节省家长时间和缓和亲子关系付费',
        decisionStyle: '被题型解析、短视频讲解和平板管控打动，重视孩子心理突破',
        coreNeeds: ['经典题型解析', '错题率下降', '家长省心和亲子关系缓和'],
        typicalBehaviors: ['看题型讲解后刷题', '整理错题和查看解析', '周末集中复习预习'],
        quotes: ['学校有 3 套教材，一套教材 3 本练习册，刷题很辛苦，而且答案还没解析。'],
      },
      {
        id: 'junior-foundation-gap',
        name: '初中｜基础断层补救型',
        definition: '疫情网课或小学基础没打牢，进入初中后跟不上，希望课后及时补听、重新建立学习动力。',
        distribution: '初中中等偏下/非付费代表',
        educationPhilosophy: '先把课上听不懂的内容补回来，再谈系统提升。',
        investment: '低到中投入；需要看到成绩进步和针对性方案才愿付费',
        decisionStyle: '家长担心在线教育“喂养式”影响独立思考，要求更明确的学习计划和效果',
        coreNeeds: ['课后补弱', '针对性学习计划', '引导孩子主动思考'],
        typicalBehaviors: ['复习当天学校课程', '只在有疑问时打开洋葱', '家长难以区分不同在线教育产品'],
        quotes: ['现在都是在卖解决方案，就是他的学习计划是什么样的，有什么样的效果，比如错题本的错题率下降没。'],
      },
      {
        id: 'junior-exam-home-review',
        name: '初中｜中考自主备考型',
        definition: '临近中考，以做试卷带复习，洋葱承担知识点解惑和低压力听懂的角色。',
        distribution: '初三备考用户代表',
        educationPhilosophy: '离考试越近，越需要和考试直接相关的题、卷和解惑。',
        investment: '有付费意愿，但会衡量剩余使用周期和家中弟妹复用价值',
        decisionStyle: '学生先判断是否听得懂，家长关注能否对中考有帮助',
        coreNeeds: ['做题后的知识点补漏', '短时听懂', '真人答疑或难题解释'],
        typicalBehaviors: ['用试卷和教辅做专项题', '遇到不会再找洋葱知识点视频', '仍会用拍搜看解析'],
        quotes: ['这节课没听懂的话，那下载洋葱吧。这个上面会听得特别懂，也不会像学校这样讲半天。'],
      },
      {
        id: 'high-boarding-pressure',
        name: '高中｜住宿高压盲学型',
        definition: '大部分时间在学校，压力大、自主时间少，容易在没规划的状态下盲目学习。',
        distribution: '高中主流痛点人群',
        educationPhilosophy: '在高压环境里，最缺的不是内容，而是时间安排、学习方向和可执行计划。',
        investment: '付费敏感；时间单位计费会让住宿生觉得看不完很亏',
        decisionStyle: '先看能不能快速解决考试问题，再判断是否值得付费',
        coreNeeds: ['学习规划', '时间分配', '高效复习路径'],
        typicalBehaviors: ['自主学习时间被作业挤压', '死磕某一科或不会的题', '没有规划地刷题和问同学'],
        quotes: ['时间安排不好，随便学，拖拖拉拉。'],
      },
      {
        id: 'high-exercise-confused',
        name: '高中｜习题解惑低效型',
        definition: '知道自己知识点不懂时洋葱能帮忙，但面对综合题和难题时，不知道怎么定位视频、怎么练题。',
        distribution: '高中核心未满足需求',
        educationPhilosophy: '考试导向下，能听懂知识点还不够，更要会做题、会归纳、会迁移。',
        investment: '对付费价值感要求高，不能高效解题就觉得不够值',
        decisionStyle: '优先选择更直接的拍搜、B站专题或同学讲题，除非洋葱能更快给答案路径',
        coreNeeds: ['习题解惑', '专题讲解', '知识归纳与答题技巧'],
        typicalBehaviors: ['综合题不会定位知识点', '看解析仍看不懂', '用拍搜或问同学解决难题'],
        quotes: ['考察的知识点，3本书都有，我就不会去看。问同学也听不懂，有时候会用拍搜看解析。'],
      },
      {
        id: 'high-exam-remedy',
        name: '高中｜提分灵药寻求型',
        definition: '相比完整知识讲解，更希望得到答题技巧、知识归纳、考试方法和短平快的提分工具。',
        distribution: '高中增长机会人群',
        educationPhilosophy: '高中的学习压力要求内容更应试、更浓缩、更能立刻用于考试。',
        investment: '愿意为能直接提分和节省时间的方案投入',
        decisionStyle: '关注是否浓缩、是否有观看指南、是否贴近考试题型',
        coreNeeds: ['答题技巧', '知识框架', '考前重点和专题方法'],
        typicalBehaviors: ['寻找免费专题和合集视频', '考前突击复习', '更偏好直给的方法攻略'],
        quotes: ['我知道我不懂的知识点，洋葱能很好帮我弄明白，但是我没有时间看完。'],
      },
      {
        id: 'high-emotional-support',
        name: '高中｜情绪回血辅助型',
        definition: '高三或成绩下滑学生既有学习漏洞，也有烦躁、想家、动力不足等情绪压力，需要更轻松的辅助感。',
        distribution: '高中情绪价值机会人群',
        educationPhilosophy: '高中生不仅需要知识价值，也需要舒缓情绪、降低挫败感的学习体验。',
        investment: '对轻松、听得懂、有陪伴感的学习工具有好感，但仍受手机时间和付费价值限制',
        decisionStyle: '被“能听懂、轻松、不枯燥”吸引，但如果不能解决题和规划，付费意愿弱',
        coreNeeds: ['降低烦躁感', '轻松听懂', '有人帮忙安排下一步'],
        typicalBehaviors: ['学不会时烦躁放弃', '依赖同学讲题', '做过计划但因拖延而放弃'],
        quotes: ['什么也不会，学不进去，很烦。'],
      },
    ],
  },
  jisuanying_project: {
    framework: PORTRAIT_FRAMEWORK,
    source: '计算营行业与用户调研整合版报告、用户需求和购买决策调研报告',
    updatedBy: '编辑者',
    personas: [
      {
        id: 'remedial',
        name: '补差型',
        definition: '当前基础薄弱，希望在短周期内补齐核心漏洞。',
        distribution: '待用户库验证',
        educationPhilosophy: '先恢复信心，再建立稳定基础。',
        investment: '结果导向，愿为明确改善投入',
        decisionStyle: '关注诊断准确性、老师责任心和可见进步',
        coreNeeds: ['定位薄弱点', '个性化补差', '阶段反馈'],
        typicalBehaviors: ['成绩下降后集中搜索', '反复比较师资', '关注是否有效果'],
        quotes: [],
      },
      {
        id: 'consolidation',
        name: '巩固夯实型',
        definition: '成绩尚可，希望系统复盘并减少知识漏洞。',
        distribution: '待用户库验证',
        educationPhilosophy: '稳定比超前更重要。',
        investment: '中等、持续投入',
        decisionStyle: '比较课程体系、节奏与服务稳定性',
        coreNeeds: ['系统复习', '查漏补缺', '保持学习习惯'],
        typicalBehaviors: ['在假期集中复盘', '关注课程连续性', '看重学习规划'],
        quotes: [],
      },
      {
        id: 'speed',
        name: '巩固提速型',
        definition: '基础较好，希望提高速度、准确率和复杂题处理能力。',
        distribution: '待用户库验证',
        educationPhilosophy: '在稳定基础上追求效率。',
        investment: '中高投入',
        decisionStyle: '关注训练强度、反馈颗粒度与同层竞争',
        coreNeeds: ['提速提准', '方法迁移', '高质量练习'],
        typicalBehaviors: ['比较题目质量', '记录正确率与速度', '要求阶段测评'],
        quotes: [],
      },
      {
        id: 'advanced',
        name: '提前学型',
        definition: '当前学习能力较强，希望形成领先进度或竞赛准备。',
        distribution: '待用户库验证',
        educationPhilosophy: '能力允许时主动拓展边界。',
        investment: '高投入、长期规划',
        decisionStyle: '关注师资上限、课程深度和升学路径',
        coreNeeds: ['超前体系', '高阶思维', '长期进阶路径'],
        typicalBehaviors: ['提前规划学期', '重视同伴水平', '持续评估课程上限'],
        quotes: [],
      },
    ],
  },
};
