import type { PortraitData } from '../types/research';

export const PORTRAIT_FRAMEWORK = ['教育理念', '投入程度', '决策方式', '核心需求', '典型行为'];

export const DEFAULT_PORTRAITS: Record<string, PortraitData> = {
  default_project: {
    framework: PORTRAIT_FRAMEWORK,
    source: '洋葱学园小学家长画像调研白皮书（定性访谈 11 人、定量问卷 667 份）',
    updatedBy: '编辑者',
    personas: [
      {
        id: 'elite-planner',
        name: '精英规划师',
        definition: '理性筛选、因材施教，兼顾兴趣与应试的长期主义家长。',
        distribution: '研究原型',
        educationPhilosophy: '分数是底线，能力与兴趣是高线。',
        investment: '高投入、高陪伴',
        decisionStyle: '主动研究、多源验证后决策',
        coreNeeds: ['科学教研', '因材施教', '兴趣与校内成绩兼顾'],
        typicalBehaviors: ['主动筛选课程', '持续观察学习状态', '重视亲子沟通'],
        quotes: ['我不是让他刷题，是让他真正理解概念，分数是会跟来的。'],
      },
      {
        id: 'practical-idealist',
        name: '务实理想者',
        definition: '认可科学教育理念，但时间有限，追求校内提效与可靠托管。',
        distribution: '约 40%',
        educationPhilosophy: '不超前，先把校内基础打牢。',
        investment: '中低投入、低陪伴',
        decisionStyle: '简单比较后选择稳定方案',
        coreNeeds: ['紧扣校内', '孩子可独立使用', '稳定提分'],
        typicalBehaviors: ['使用预习功能', '关注续费性价比', '向熟人推荐'],
        quotes: ['只要成绩稳住、孩子自己能用，我就觉得够了。'],
      },
      {
        id: 'anxious-investor',
        name: '焦虑投资者',
        definition: '高投入但缺少稳定方法，容易受成绩波动和外部信息驱动。',
        distribution: '研究原型',
        educationPhilosophy: '理念摇摆，结果压力优先。',
        investment: '高投入、分散购买',
        decisionStyle: '熟人推荐或即时反馈驱动',
        coreNeeds: ['明确效果', '学习路径', '降低家长无力感'],
        typicalBehaviors: ['频繁购买课程', '成绩波动时更换方案', '关注短期反馈'],
        quotes: ['别人报什么我就跟着报，总怕孩子落后。'],
      },
      {
        id: 'permissive-observer',
        name: '放任观望者',
        definition: '教育规划和投入较弱，主要跟随孩子意愿。',
        distribution: '研究原型',
        educationPhilosophy: '顺其自然，减少额外压力。',
        investment: '低投入、低陪伴',
        decisionStyle: '孩子喜欢就购买',
        coreNeeds: ['低门槛', '不增加压力', '孩子自驱'],
        typicalBehaviors: ['较少主动搜索', '低频查看进度', '按孩子意愿续费'],
        quotes: ['他喜欢就买，用不用得起来看他自己。'],
      },
    ],
  },
  jisuanying_project: {
    framework: PORTRAIT_FRAMEWORK,
    source: '计算营行业与用户调研整合版报告、用户需求和购买决策调研报告',
    updatedBy: '编辑者',
    personas: [
      {
        id: 'remedial',
        name: '补差型',
        definition: '当前基础薄弱，希望在短周期内补齐核心漏洞。',
        distribution: '待用户库验证',
        educationPhilosophy: '先恢复信心，再建立稳定基础。',
        investment: '结果导向，愿为明确改善投入',
        decisionStyle: '关注诊断准确性、老师责任心和可见进步',
        coreNeeds: ['定位薄弱点', '个性化补差', '阶段反馈'],
        typicalBehaviors: ['成绩下降后集中搜索', '反复比较师资', '关注是否有效果'],
        quotes: [],
      },
      {
        id: 'consolidation',
        name: '巩固夯实型',
        definition: '成绩尚可，希望系统复盘并减少知识漏洞。',
        distribution: '待用户库验证',
        educationPhilosophy: '稳定比超前更重要。',
        investment: '中等、持续投入',
        decisionStyle: '比较课程体系、节奏与服务稳定性',
        coreNeeds: ['系统复习', '查漏补缺', '保持学习习惯'],
        typicalBehaviors: ['在假期集中复盘', '关注课程连续性', '看重学习规划'],
        quotes: [],
      },
      {
        id: 'speed',
        name: '巩固提速型',
        definition: '基础较好，希望提高速度、准确率和复杂题处理能力。',
        distribution: '待用户库验证',
        educationPhilosophy: '在稳定基础上追求效率。',
        investment: '中高投入',
        decisionStyle: '关注训练强度、反馈颗粒度与同层竞争',
        coreNeeds: ['提速提准', '方法迁移', '高质量练习'],
        typicalBehaviors: ['比较题目质量', '记录正确率与速度', '要求阶段测评'],
        quotes: [],
      },
      {
        id: 'advanced',
        name: '提前学型',
        definition: '当前学习能力较强，希望形成领先进度或竞赛准备。',
        distribution: '待用户库验证',
        educationPhilosophy: '能力允许时主动拓展边界。',
        investment: '高投入、长期规划',
        decisionStyle: '关注师资上限、课程深度和升学路径',
        coreNeeds: ['超前体系', '高阶思维', '长期进阶路径'],
        typicalBehaviors: ['提前规划学期', '重视同伴水平', '持续评估课程上限'],
        quotes: [],
      },
    ],
  },
};
